### ISSUE TITLE
A situation that I see and cannot perceive while translating.

### ISSUE THREAD

**Issue by Zaryob** [Slackadays/Clipboard#10]
Hi,
I added Turkish translations and while making this, I see some problems.  I want to list them and discuss.

The ActionArray we entered as `actions` is taken directly as the action of the clipboard. In this case, when I localize these operations in language.hpp, I call them with their localized version. Is this an expected behavior? If not, let's create something called `actionNames` instead of `actions` and pull the names from there, and use the actions variable to operate the operations. In this way, it can work with the same commands in every language, even if it is localized. Of course, this is just a suggestion.

**Comment by Slackadays** [comment]
This is expected behavior, as "cut, copy, and paste" isn't some term to refer to some specific idea that only exists in English.

**Comment by Zaryob** [comment]
Got it sir! What about shortcut btw. They are currently dependent with lang.

**Comment by Slackadays** [comment]
I don't know what to do for shortcuts, but perhaps because they're so short, they can stay hard-coded and become their "own thing" like with the GNU Coreutils where you can forget `cp` and `mv` mean "copy" and "move."

**Comment by Zaryob** [comment]
I thing it must be also translatable but. Anyways. Both of them will work no matter.

**Comment by Slackadays** [comment]
Would it work if I made the shortcuts translatable? This will delay the merge one more time

**Comment by Slackadays** [comment]
Now in the latest commit https://github.com/Slackadays/Clipboard/commit/e44f9ce67bb745344fd7f9b74e08bad7b1436cf4

**Comment by Zaryob** [comment]
Okkey.
