### ISSUE TITLE
cb doesn't see images copied to the clipboard

### ISSUE THREAD

**Issue by Mart-Bogdan** [Slackadays/Clipboard#101]
**Describe the bug**
Cb isn't able to see images copied from following applications:
* Google Chrome (didn't test on chromium, but I think it would behave same)
* Gimp
* Telegram
* Firefox

**To Reproduce**
1. Copy image in appropriate application
2. Run `cb` in terminal
```
[winnie@bm-linux-nitro517 ~]$ cb
• There is currently nothing in the clipboard.
Add cut, copy, or paste to the end, like clipboard copy to get started, or if you need help, try clipboard -h to show the help screen.
```

**Expected behavior**
Clipboard app should see images, being able to save them as files, or pipe them as binary content to stdout (to be able to view with icat or forward to ImageMagick) 

**Screenshots**
This content looks differently in different applications as source:
* Gimp:   it's `image/png` only
![image](https://user-images.githubusercontent.com/775038/221725736-07c77e53-a0c9-4ffe-a304-1ff4f7e3729e.png)

* Telegram: also `image/png` 
* Firefox: `image/png` + `text/html` (html with <img> tag in it):
![image](https://user-images.githubusercontent.com/775038/221726125-33adc48c-7179-4b6a-ba27-e25845e226e0.png)
```html
<meta http-equiv="content-type" content="text/html; charset=utf-8"><img src="http://127.0.0.1:8000/static/ui/img/three-best-canadianflooring-toronto-2021.png" alt="Best Flooring companies in Toronto">
```
* Chrome 
It's wierd one, it has text/html with img tag and text/plain with URL of image, but not actual binary data:
![image](https://user-images.githubusercontent.com/775038/221726541-8f2bfcf7-1284-446a-aeab-2d34337c37c9.png)

```html
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/280px-Tux.svg.png" alt="Tux — Вікіпедія"/>
```

But I can paste images from all this ources into Telegram an they are detected as images and creates Photo attachment.
I also can paste this images into web browser, into Gmail.

**Additional context**

Answer these questions so that we can help you faster:
- [x] If I compiled Clipboard myself, then the errors don't mention "LTO error" (this is a bug with the compiler, not Clipboard)
- [x] If I compiled Clipboard myself, then the errors don't mention "XYZ has not been defined in namespace std" (this usually means you need a compiler with C++20 support, so upgrade first)
- [ ] I check these boxes without reading them (checking this one will make your bug report invalid!)
- [x] I am using the latest commit/release (we only support the latest)
- [ ] If I downloaded Clipboard from GitHub Actions or with the install script, then the errors don't mention "GLIBC XYZ not found" (your system is too outdated for Clipboard, so upgrade it)

**System Specs**

OS: Manjaro Linux
Installed version: https://github.com/Slackadays/Clipboard/commit/4bba3f73fec0c35794eb920d791e119b669e8b2e
Display server: X11
DE: KDE Plasma 5.26.5

**Comment by Mart-Bogdan** [comment]
Even as Chrome provides `text/plain` with URL.

it doesn't show in app :-(

Showing output of debug build:
```
Found getX11Clipboard in libclipboardx11.so, calling it
Opening X11 connection
Waiting for event 28
No pollUntilReturn data, sleeping
No pollUntilReturn data, sleeping
pollUntilReturn finished successfully, got a result
Waiting for event 31
No pollUntilReturn data, sleeping
pollUntilReturn finished successfully, got a result
No supported MIME Type, aborting
Closing X11 connection
Found getWaylandClipboard in libclipboardwayland.so, calling it
Error getting clipboard data: Failed to initialize wl_display
• There is currently nothing in the clipboard.
Add cut, copy, or paste to the end, like clipboard copy to get started, or if you need help, try clipboard -h to show the help screen.
```

**Comment by Slackadays** [comment]
For this issue, the crux of the issue is a lack of MIME types loaded up in the Clipboard backends. However, even after choosing a MIME type manually, there's a segmentation fault because of some lookup issue, which requires more work to solve. Also, once we get the right MIME type, we need to know if we want to save this as raw data or as a file. Saving as a file will require some other MIME inference code that I have queued up for later but I think is the best option.

**Comment by Slackadays** [comment]
@Davipb Sorry for the ping, but I just realized that the TARGETS trick you mentioned would be useful here. The X11 code should try to find the best MIME type first, then fall back to something from TARGETS. Only then should the MIME code fall back to plain text if available, which I noticed in testing doesn't always work.

**Comment by Davipb** [comment]
This is not a bug, but rather by design. Since CB itself only supports files and text, we also only check for files and text when pulling data from the native clipboard. Pulling other data types would require CB itself to support other data types, which is a larger feature that requires some redesign of the core code.

**Comment by Mart-Bogdan** [comment]
Perhaps unrecognized content types can be treated as files/binaries? 

I don't know, perhaps priority ti mime types should be introduced. 

And if files require file name, i don't know. Perhaps it can be asked from user, or be auto generated. And perhaps MIME database could be queried to get default file extention for mime type, to generate smth like clipboar123.png

**Comment by Slackadays** [comment]
Added initial MIME type reading from the GUI in https://github.com/Slackadays/Clipboard/commit/30791178c58c2f96eb6bca06b9aadc2d514af75d

**Comment by Slackadays** [comment]
Added in https://github.com/Slackadays/Clipboard/commit/04b34aa7bb3f26dd2d2d18d8df894b378b07fdf6, it turns out this was as simple as adding a few lines of code (no MIME inference needed!)

**Comment by Slackadays** [comment]
In the future, we may want to be able to write the right file when you paste CB's clipboard, but that will require a couple more changes.

**Comment by Mart-Bogdan** [comment]
Hi, @Slackadays .

so this:
```
    insert("image/jxl", ClipboardContentType::Text);
    insert("image/png", ClipboardContentType::Text);
 ```
 means that image would be spit into stdout?

**Comment by Mart-Bogdan** [comment]
Oh, that's disapointment. Looks like icat doesn't support reading from stdin :-(

**Comment by Slackadays** [comment]
> Hi, @Slackadays .
> 
> so this:
> 
> ```
>     insert("image/jxl", ClipboardContentType::Text);
>     insert("image/png", ClipboardContentType::Text);
> ```
> 
> means that image would be spit into stdout?

Exactly, but like in your last comment, the thing you use stdout with has to be able to work with it. :(
