### ISSUE TITLE
Flashes in kitty terminal

### ISSUE THREAD

**Issue by kohane27** [Slackadays/Clipboard#106]
Hello there. Hope you're doing well. Thank you for creating `clipboard`.

However, I have encountered this weird flashing issue below:

https://user-images.githubusercontent.com/57322459/232660441-55905ed6-54a1-4f7c-a040-7f2f67cf5d75.mp4

This flashing issue seems to affect both [kitty](https://github.com/kovidgoyal/kitty) and [Alacritty](https://github.com/alacritty/alacritty):

https://user-images.githubusercontent.com/57322459/232660544-5bf04702-8263-485f-8900-952a4a080bb9.mp4

## System info

```
cb --help
Clipboard 0.6.0 (commit d399781)

sway --version
sway version 1.8.1

Kernel: Linux 6.2.11-arch1-1
```

Any input is much appreciated. Thank you!

**Comment by kohane27** [comment]
As mentioned in [Environment Variables](https://github.com/Slackadays/Clipboard#-13):

```
Debug a flaky GUI system by disabling its integration with Clipboard.

$ CLIPBOARD_NOGUI=1 cb show
$ export CLIPBOARD_NOGUI=1
$ cb show
```

Once I set `CLIPBOARD_NOGUI=1`, this flashing is gone. Thanks again!

**Comment by Slackadays** [comment]
This is actually an issue with Wayland, and one that Clipboard can't fix without doing some funky non-standards-compliant stuff to take advantage of specific protocols. Clipboard makes a temporary window to get focus in order to get the clipboard content, because Wayland doesn't allow non-focused apps to get clipboard content for security.

**Comment by kohane27** [comment]
Thank you for the explanation. Hopefully this issue is helpful to other with similar situation. Thank you again for this great application!

**Comment by hillosipuli** [comment]
How does [wl-clipboard](https://github.com/bugaevc/wl-clipboard) manage to access clipboard contents without temporary window? That quick temporary window manages to sometimes crash firefox on my build of dwl (like dwm but for wayland) and is thus quite annoying.

**Comment by Slackadays** [comment]
@hillosipuli if this becomes a bigger problem, I can try messing around with Wayland to see if that can be fixed.

**Comment by alteriks** [comment]
@kohane27 I've managed to circumvent this issue by using this rule in my sway config:
```
for_window [title="^Clipboard$"] border none, floating enable
```
