### ISSUE TITLE
Full MIME support

### ISSUE THREAD

**Issue by flying-sheep** [Slackadays/Clipboard#107]
**Is your feature request related to a problem? Please describe.**
I want to inspect and modify what an application put into the clipboard.

E.g. a terminal emulator might put some `text/plain` version of copied text in there, next to some `text/html` content with the colored version of the same text. I would like to be able to paste the `text/html` version to a file or move it to `text/plain` using `cb load` or so, so when I paste into a text editor (using Ctrl-V), it pastes the HTML code and not the uncolored text.

**Describe the solution you'd like**
All commands should be integrated with the existence of multiple mime types:

- `cb show` and/or `cb info` should show what mime types are available in the data
- `cb load` should allow modifying what mime type data is stored as
- `cb paste` should allow to select which mime type to paste

**Describe alternatives you've considered**
A limited alternative could be replacing the pipe interface of `cb paste` with a `--outfile=name.ext` interface. Then the chosen MIME type could be inferred from the file extension. I can’t think of anything else. 

**Additional context**
[`wl-clipboard`](https://github.com/bugaevc/wl-clipboard) is a nice (but very technical/low level) tool with a CLI interface for handling multiple mime types. Maybe it can be used for inspiration.

**Comment by Slackadays** [comment]
Unfortunately, this might be a huge pain because CB doesn't actually have any idea of MIME type, just raw data. And, the fact that it even works with GUI systems that have MIME types is a pure afterthought, a bonus. However, one really simple way to add this feature is a `--mime`` flag that simply requests the given MINE type. That way it should just work with all the commands where it's applicable and it doesn't change the way they work.

**Comment by flying-sheep** [comment]
> one really simple way to add this feature is a --mime flag that simply requests the given MINE type

Would that work? For my use case, would e.g. `cb --mime=text/html | cb` grab the `text/html` data from clipboard 0 and then store it in clipboard 0’s `text/plain` slot?

Seems like the design might have to be a bit more complex (or the implementation really smart) to make that use case possible?

**Comment by Slackadays** [comment]
CB doesn't actually have any slots, since raw data is just stored as a file in the special "clipboard filesystem." So, the way the flag would work is to simply request the given MIME type from the GUI clipboard system and see if it's offered up or not. On the plus side, you wouldn't need to do `cb --mime=text/html | cb` because CB automatically grabs the GUI clipboard whenever you have a "reading" action like pasting or showing.

**Comment by flying-sheep** [comment]
> you wouldn't need to do `cb --mime=text/html | cb`

The purpose of that would be to have the former `text/html` entry stored in the `text/plain` entry of the GUI clipboard, allowing me to paste HTML code into a text editor.

**Comment by Slackadays** [comment]
@flying-sheep Done, added in https://github.com/Slackadays/Clipboard/commit/212e4614ab9aca2977adc56a9c2db5550e915230, so now you can do `cb -m text/html | cb` or `cb --mime text/html | cb` to load HTML content into the main clipboard.

**Comment by flying-sheep** [comment]
Sounds great to me!

**Comment by Slackadays** [comment]
Would a JSON output for the Info command work along with providing the available types? If you just run it in a regular terminal, it would then look like
```
Size: 100B
Content type: text/plain, text/html, etc
Note: Blah blah blah...
```
But the JSON output might look like
```
{
    "size": "100B",
    "availableTypes": [
        "text/plain",
        "text/html"
    ]
}
```
You would get this by doing `cb info | something` to get the pipe output.

**Comment by Slackadays** [comment]
@flying-sheep MIME type listing is now available in https://github.com/Slackadays/Clipboard/commit/75604073e4efc88db5a51401c357ca45d18b4eda, would you also like a serialized format like in the comment above?

**Comment by flying-sheep** [comment]
I think MIME types can’t contain spaces, right? So a space delimited list should be fine? I didn’t verify this though.

**Comment by Slackadays** [comment]
I don't think they can, so lost should just be fine. However, the list won't just have MIME types because it'll be for the whole Info action. This method would actually match what the Linux /proc system does, so there's that.
