### ISSUE TITLE
Clipboard sometimes copies text as an image

### ISSUE THREAD

**Issue by MiguelGuthridge** [Slackadays/Clipboard#112]
**Describe the bug**
I have a simple alias that copies a UNIX timestamp to my clipboard

```sh
alias unixtime="date +%s | tee >(cb copy)"
```

<pre><span style="color:#D0CFCC"><b>| </b></span><span style="color:#26A269"><b>migue@yzma</b></span><span style="color:#D0CFCC"><b> ::</b></span> <span style="color:#12488B"><b>~</b></span>  
<span style="color:#2AA1B3"><b>⋙  </b></span> unixtime
1682490354
<span style="color:#00D700">✅ Copied 11B</span></pre>

However I noticed for certain values, it seemed to copy the output as an image rather than as text.

Here is an example image it copied:
![image](https://user-images.githubusercontent.com/31365175/234488818-7ccfa5e7-96b7-4fa7-9fb4-ccc83359709a.png)

My clipboard manager indicates that this image has a resolution of `-1x-1`, which is probably why it's giving an error.

Here is the value it should have copied instead:
> 1682490354

**To Reproduce**

`echo 1682490354 | cb copy`

**Expected behavior**

The text `1682490354` is copied.

**Version**
* 0.6.0 (commit 519207e), installed with the install script

**Questionnaire**
Check these boxes to see if your issue is valid or not.
- [x] If I compiled CB, then any errors that may be present don't mention "LTO error" (this is sadly a bug with the compiler, not Clipboard)
- [x] If I compiled CB, then any errors that may be present don't mention "XYZ has not been defined in namespace std" (this sadly means you need a compiler with C++20 support, so upgrade first)
- [ ] I check all these boxes without reading them ***[I see what you did there]***
- [ ] I think bachata is the best music ***[I haven't listened, should I?]***
- [x] I'm using the latest commit/release (we only support the latest)
- [x] #113

**Additional context**
It may be that there is no way to tell the difference between this string and the binary data for an image. If that's the case, maybe a solution would be to add a command line flag to force `cb` to copy something as text rather than as an image (or file, or anything else).

```sh
echo 1682490354 | cb copy --text
```

I had a look and couldn't find a flag like this, but apologies if I missed it :)

Thanks for your work!

**Comment by Slackadays** [comment]
I think I know the problem here, but the fix might be a little funky to add since it depends on some hardcoded values in the backend code.

**Comment by Slackadays** [comment]
@MiguelGuthridge Done, fixed in https://github.com/Slackadays/Clipboard/commit/7c7aff932fc605d0ac1a2f055259ef382d50a4c9

I just took this screenshot showing the proper MIME type handling now :)

![image](https://user-images.githubusercontent.com/69403549/234646940-60ff14c3-1ce2-4643-bde9-e797942542e0.png)
