### ISSUE TITLE
Is it possible to install `cb` without sudo privileges?

### ISSUE THREAD

**Issue by MiguelGuthridge** [Slackadays/Clipboard#123]
**Is your feature request related to a problem? Please describe.**
I want to run `cb` on my university systems, but since I am not a sudoer, I cannot install it.

While I could install it manually, this isn't the optimal user experience (hence this feature request).

**Describe the solution you'd like**
Add an option to allow `cb` to be installed to the `~/.local/bin` directory (perhaps through a different installation script or a "do you want to install this for yourself or for all users" check when running the installation script).

**Describe alternatives you've considered**
* I could beg my university sysadmins to add your tool (unlikely to work)
* I could trial-and-error until I figure out where to put the binary and its libraries myself
* The specific locations for where to put the executable and its dependencies could be documented

**Additional context**
Thanks for your work! This is by-far one of my favourite projects on GitHub!

**Comment by Antiz96** [comment]
You can just grab the prebuilt binary from the latest release and unpack it `~/.local/bin`

**Comment by Slackadays** [comment]
There is also now a Flatpak that should work without root

**Comment by MiguelGuthridge** [comment]
@Antiz96 looks like there are some libraries as well - I'd need to investigate further.

**Comment by MiguelGuthridge** [comment]
@Slackadays sadly my uni doesn't support flatpaks

**Comment by Slackadays** [comment]
What about compiling it?

**Comment by MiguelGuthridge** [comment]
I'm definitely going to look into it! This issue is more intended to get support for single-user installations in the install script. Apologies if I didn't make that clear in the issue originally.

**Comment by MiguelGuthridge** [comment]
Another potential solution could be some documentation to show where to put everything if installing locally.

**Comment by Slackadays** [comment]
@MiguelGuthridge does the new documentation and install script work for you? It should be able to check for sudo compatibility and the documentation is a lot more comprehensive

**Comment by MiguelGuthridge** [comment]
Sadly the install script did not work as expected:

```
| z5312085@vx11 :: ~  
⋙   curl -sSL https://github.com/Slackadays/Clipboard/raw/main/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  265k    0  265k    0     0  85375      0 --:--:--  0:00:03 --:--:--  309k
Archive:  clipboard-linux.zip
   creating: bin/
   creating: lib/
  inflating: bin/cb                  
  inflating: lib/libcbwayland.so     
  inflating: lib/libcbx11.so         
  inflating: lib/libgui.a            
Sorry, user z5312085 is not allowed to execute '/usr/bin/mv bin/cb /import/kamen/5/z5312085/.local/bin/cb' as root on vx11.orchestra.cse.unsw.EDU.AU.
```

Looks like it's trying to copy to the right place, but still wants to use sudo. I'll take a glance and create a PR if it's as simple as it looks like it'll be :)

**Comment by MiguelGuthridge** [comment]
Looks like my university doesn't keep their libraries updated, so the install fails for me (will be trying to compile from source), but it should work for others.

```
| z5312085@vx11 :: ~  
⋙   curl -sSL https://github.com/MiguelGuthridge/Clipboard/raw/patch-1/install.sh | sh                                                                                                                              ⏎
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  265k    0  265k    0     0  93393      0 --:--:--  0:00:02 --:--:--  315k
Archive:  clipboard-linux.zip
   creating: bin/
   creating: lib/
  inflating: bin/cb                  
  inflating: lib/libcbwayland.so     
  inflating: lib/libcbx11.so         
  inflating: lib/libgui.a            
/import/kamen/5/z5312085/.local/bin/cb
cb: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by cb)
cb: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by cb)
cb: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by cb)
cb: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by cb)
Sorry, but this installer script doesn't support this system.
💡 However, you can still install CB using the other methods in the readme!
```

**Comment by Slackadays** [comment]
Done :)
