### ISSUE TITLE
Availability on flathub

### ISSUE THREAD

**Issue by bestlibre** [Slackadays/Clipboard#125]
I've seen in the latest release notes that clipboard is available as a flatpack. Have you considered putting it on flathub ?

Thanks for your work !

**Comment by Slackadays** [comment]
@bestlibre now all we need to do is wait for Flathub to accept Clipboard https://github.com/flathub/flathub/pull/4210

**Comment by Slackadays** [comment]
@bestlibre we are now on Flathub! do `flatpak install app.getclipboard.Clipboard` to install it in one step. :tada:
