### ISSUE TITLE
"cb copy" doesn't integrate with system clipboard on wayland/xwayland

### ISSUE THREAD

**Issue by alteriks** [Slackadays/Clipboard#126]
**Describe the bug**
"cb copy" doesn't integrate with system clipboard on wayland/xwayland.
"cb paste" works properly. Both commands work under Xorg. 

**To Reproduce**
```
wl-copy --clear
wl-paste

cb copy "copy text using cb"
cb status
wl-paste
# Try paste with ctrl+v
# Nothing is pasted here ;/
```

**Expected behavior**
cb should integrate with system clipboard  

**Screenshots**
cb-copy doesn't work:
[cb_copy.webm](https://github.com/Slackadays/Clipboard/assets/6512767/78c81bcb-e518-4baa-9da8-f0a08cf55778)
```
LD_DEBUG=libs cb copy "copy text using cb"
   2994541:	find library=libstdc++.so.6 [0]; searching
   2994541:	search path=/usr/lib/glibc-hwcaps/x86-64-v3:/usr/lib/glibc-hwcaps/x86-64-v2:/usr/lib		(system search path)
   2994541:	 trying file=/usr/lib/glibc-hwcaps/x86-64-v3/libstdc++.so.6
   2994541:	 trying file=/usr/lib/glibc-hwcaps/x86-64-v2/libstdc++.so.6
   2994541:	 trying file=/usr/lib/libstdc++.so.6
   2994541:	
   2994541:	find library=libgcc_s.so.1 [0]; searching
   2994541:	search path=/usr/lib		(system search path)
   2994541:	 trying file=/usr/lib/libgcc_s.so.1
   2994541:	
   2994541:	find library=libc.so.6 [0]; searching
   2994541:	search path=/usr/lib		(system search path)
   2994541:	 trying file=/usr/lib/libc.so.6
   2994541:	
   2994541:	find library=libm.so.6 [0]; searching
   2994541:	search cache=/etc/ld.so.cache
   2994541:	 trying file=/usr/lib/libm.so.6
   2994541:	
   2994541:	
   2994541:	calling init: /lib64/ld-linux-x86-64.so.2
   2994541:	
   2994541:	
   2994541:	calling init: /usr/lib/libc.so.6
   2994541:	
   2994541:	
   2994541:	calling init: /usr/lib/libm.so.6
   2994541:	
   2994541:	
   2994541:	calling init: /usr/lib/libgcc_s.so.1
   2994541:	
   2994541:	
   2994541:	calling init: /usr/lib/libstdc++.so.6
   2994541:	
   2994541:	
   2994541:	initialize program: cb
   2994541:	
   2994541:	
   2994541:	transferring control: cb
   2994541:	
✅ Copied text "copy text using cb"
   2994541:	find library=libcbx11.so [0]; searching
   2994541:	search path=/usr/lib		(system search path)
   2994541:	 trying file=/usr/lib/libcbx11.so
   2994541:	
   2994541:	find library=libX11.so.6 [0]; searching
   2994541:	search cache=/etc/ld.so.cache
   2994541:	 trying file=/usr/lib/libX11.so.6
   2994541:	
   2994541:	find library=libxcb.so.1 [0]; searching
   2994541:	search cache=/etc/ld.so.cache
   2994541:	 trying file=/usr/lib/libxcb.so.1
   2994541:	
   2994541:	find library=libXau.so.6 [0]; searching
   2994541:	search cache=/etc/ld.so.cache
   2994541:	 trying file=/usr/lib/libXau.so.6
   2994541:	
   2994541:	find library=libXdmcp.so.6 [0]; searching
   2994541:	search cache=/etc/ld.so.cache
   2994541:	 trying file=/usr/lib/libXdmcp.so.6
   2994541:	
   2994541:	
   2994541:	calling init: /usr/lib/libXdmcp.so.6
   2994541:	
   2994541:	
   2994541:	calling init: /usr/lib/libXau.so.6
   2994541:	
   2994541:	
   2994541:	calling init: /usr/lib/libxcb.so.1
   2994541:	
   2994541:	
   2994541:	calling init: /usr/lib/libX11.so.6
   2994541:	
   2994541:	
   2994541:	calling init: /usr/lib/libcbx11.so
   2994541:	
   2994541:	
   2994541:	calling fini:  [0]
   2994541:	
   2994541:	
   2994541:	calling fini: /usr/lib/libcbx11.so [0]
   2994541:	
   2994541:	
   2994541:	calling fini: /usr/lib/libstdc++.so.6 [0]
   2994541:	
   2994541:	
   2994541:	calling fini: /usr/lib/libgcc_s.so.1 [0]
   2994541:	
   2994541:	
   2994541:	calling fini: /usr/lib/libm.so.6 [0]
   2994541:	
   2994541:	
   2994541:	calling fini: /usr/lib/libX11.so.6 [0]
   2994541:	
   2994541:	
   2994541:	calling fini: /usr/lib/libxcb.so.1 [0]
   2994541:	
   2994541:	
   2994541:	calling fini: /usr/lib/libXau.so.6 [0]
   2994541:	
   2994541:	
   2994541:	calling fini: /usr/lib/libXdmcp.so.6 [0]
   2994541:	
   2994541:	
   2994541:	calling fini: /usr/lib/libc.so.6 [0]
   2994541:	
   2994541:	
   2994541:	calling fini: /lib64/ld-linux-x86-64.so.2 [0]
   2994541:	
```

`wl-copy` and `cb paste` work properly
[wl-copy.webm](https://github.com/Slackadays/Clipboard/assets/6512767/c3cad0eb-f904-4775-844a-498e028c9d6e)

**Version**
Newest cb installed from aur. 
```
clipboard 0.8.0-1
sway 1:1.8.1-1
wayland 1.22.0-1
wayland-protocols 1.31-1
wl-clipboard 1:2.1.0-3
```
![2023-06-06_17-53](https://github.com/Slackadays/Clipboard/assets/6512767/b3889297-5807-46b1-ac35-7647170ba5e6)

**Questionnaire**
Check these boxes to see if your issue is valid or not.
- [x] If I compiled CB, then any errors that may be present don't mention "LTO error" (this is sadly a bug with the compiler, not Clipboard)
- [x] If I compiled CB, then any errors that may be present don't mention "XYZ has not been defined in namespace std" (this sadly means you need a compiler with C++20 support, so upgrade first)

**Comment by Slackadays** [comment]
Does `xclip` work? Because this could be an xwayland issue, as CB doesn't do anything with Wayland unless X11 fails.

**Comment by alteriks** [comment]
yes xclip works under i3wm/Xorg session
![image](https://github.com/Slackadays/Clipboard/assets/6512767/15c3aad5-2aa1-4723-95f6-2de9de5f9131)

**Comment by Slackadays** [comment]
does it work the other way? it looks like you only reported it not working with copying with CB first and then reading with wl-paste, but I'd like to know if copying with wl-copy and xclip and then reading with cb doesn't work

**Comment by alteriks** [comment]
Copying with `wl-copy` and pasting with `cb paste` works fine

Please watch second vid from my first comment - https://github.com/Slackadays/Clipboard/assets/6512767/c3cad0eb-f904-4775-844a-498e028c9d6e

**Comment by alteriks** [comment]
Removing /usr/lib/libcbx11.so makes `cb copy` work as intended
![2023-06-06_18-11](https://github.com/Slackadays/Clipboard/assets/6512767/afd2f675-1b07-4906-832c-aa4caaa8e4f0)

Please verify this output, here `/usr/lib/libcbwayland.so` is called because `/usr/lib/libcbx11.so` is missing
```
LD_DEBUG=libs cb copy "copy text using cb"
   3090817:	find library=libstdc++.so.6 [0]; searching
   3090817:	search path=/usr/lib/glibc-hwcaps/x86-64-v3:/usr/lib/glibc-hwcaps/x86-64-v2:/usr/lib		(system search path)
   3090817:	 trying file=/usr/lib/glibc-hwcaps/x86-64-v3/libstdc++.so.6
   3090817:	 trying file=/usr/lib/glibc-hwcaps/x86-64-v2/libstdc++.so.6
   3090817:	 trying file=/usr/lib/libstdc++.so.6
   3090817:	
   3090817:	find library=libgcc_s.so.1 [0]; searching
   3090817:	search path=/usr/lib		(system search path)
   3090817:	 trying file=/usr/lib/libgcc_s.so.1
   3090817:	
   3090817:	find library=libc.so.6 [0]; searching
   3090817:	search path=/usr/lib		(system search path)
   3090817:	 trying file=/usr/lib/libc.so.6
   3090817:	
   3090817:	find library=libm.so.6 [0]; searching
   3090817:	search cache=/etc/ld.so.cache
   3090817:	 trying file=/usr/lib/libm.so.6
   3090817:	
   3090817:	
   3090817:	calling init: /lib64/ld-linux-x86-64.so.2
   3090817:	
   3090817:	
   3090817:	calling init: /usr/lib/libc.so.6
   3090817:	
   3090817:	
   3090817:	calling init: /usr/lib/libm.so.6
   3090817:	
   3090817:	
   3090817:	calling init: /usr/lib/libgcc_s.so.1
   3090817:	
   3090817:	
   3090817:	calling init: /usr/lib/libstdc++.so.6
   3090817:	
   3090817:	
   3090817:	initialize program: cb
   3090817:	
   3090817:	
   3090817:	transferring control: cb
   3090817:	
✅ Copied text "copy text using cb"
   3090817:	find library=libcbx11.so [0]; searching
   3090817:	search path=/usr/lib		(system search path)
   3090817:	 trying file=/usr/lib/libcbx11.so
   3090817:	search cache=/etc/ld.so.cache
   3090817:	 trying file=/usr/lib/libcbx11.so
   3090817:	search path=/usr/lib		(system search path)
   3090817:	 trying file=/usr/lib/libcbx11.so
   3090817:	
   3090817:	find library=libcbwayland.so [0]; searching
   3090817:	search path=/usr/lib		(system search path)
   3090817:	 trying file=/usr/lib/libcbwayland.so
   3090817:	
   3090817:	find library=libwayland-client.so.0 [0]; searching
   3090817:	search cache=/etc/ld.so.cache
   3090817:	 trying file=/usr/lib/libwayland-client.so.0
   3090817:	
   3090817:	find library=libffi.so.8 [0]; searching
   3090817:	search cache=/etc/ld.so.cache
   3090817:	 trying file=/usr/lib/libffi.so.8
   3090817:	
   3090817:	
   3090817:	calling init: /usr/lib/libffi.so.8
   3090817:	
   3090817:	
   3090817:	calling init: /usr/lib/libwayland-client.so.0
   3090817:	
   3090817:	
   3090817:	calling init: /usr/lib/libcbwayland.so
   3090817:	
   3090817:	
   3090817:	calling fini:  [0]
   3090817:	
   3090817:	
   3090817:	calling fini: /usr/lib/libcbwayland.so [0]
   3090817:	
   3090817:	
   3090817:	calling fini: /usr/lib/libstdc++.so.6 [0]
   3090817:	
   3090817:	
   3090817:	calling fini: /usr/lib/libgcc_s.so.1 [0]
   3090817:	
   3090817:	
   3090817:	calling fini: /usr/lib/libm.so.6 [0]
   3090817:	
   3090817:	
   3090817:	calling fini: /usr/lib/libwayland-client.so.0 [0]
   3090817:	
   3090817:	
   3090817:	calling fini: /usr/lib/libffi.so.8 [0]
   3090817:	
   3090817:	
   3090817:	calling fini: /usr/lib/libc.so.6 [0]
   3090817:	
   3090817:	
   3090817:	calling fini: /lib64/ld-linux-x86-64.so.2 [0]
   3090817:	
```

In my first comment `/usr/lib/libcbwayland.so`  doesn't get called

**Comment by Slackadays** [comment]
Then this is an xwayland bug, and here's why:

Consider that CB will only do Wayland if X11 fails. We can see from your initial logs that CB is only doing X11. Therefore, everything has to go through xwayland to get to Wayland.

Now that `wl-paste` fails, we know Wayland doesn't work. However, `xclip` does, so X11 works. Therefore, this is an xwayland bug.

**Comment by Slackadays** [comment]
For your next steps, I would say to either keep that X11 library disabled, or set the secret `CLIPBOARD_REQUIREWAYLAND` environment variable to `1` to always do Wayland.

**Comment by alteriks** [comment]
> does `xclip` work though? I'm trying to rule out an xwayland issue which would prevent an X11 application from writing to the clipboard which get picked up by Wayland. CB works transparently with both X11 and Wayland so we need to try out all combinations of `xclip` and `wl-clipboard`

![2023-06-06_18-20](https://github.com/Slackadays/Clipboard/assets/6512767/1c702a5d-5f6c-4310-a375-25c7941e0f22)

**Comment by Slackadays** [comment]
Then this is definitely an xwayland bug because CB would be using Wayland here which has to go through xwayland to get the `xclip` copies, which isn't working.

**Comment by alteriks** [comment]
> Then this is definitely an xwayland bug because CB would be using Wayland here which has to go through xwayland to get the `xclip` copies, which isn't working.

Maybe you could verify if wayland runs instead of using xwayland? It seems that wayland handles clipboard in both ways between wayland<->xwayland apps
![2023-06-06_18-28](https://github.com/Slackadays/Clipboard/assets/6512767/64607aae-cf96-416d-a4b5-930b9b1065f7)

**Comment by Slackadays** [comment]
The tricky part is that I believe I did do that a while ago so that Wayland would get priority first, but a bunch of tests kept failing for some weird reason and doing X11 first was the fix. However, I can try that again and see if it's improved at all. :)

**Comment by Slackadays** [comment]
@alteriks does the latest commit work for you? X11 and Wayland are swapped again as well as a potential fix for the funky characters you're seeing in the terminal

**Comment by Slackadays** [comment]
@alteriks How about now? It should try to clear out the funky characters after this one change I made.

**Comment by alteriks** [comment]
@Slackadays Funky keys are gone, but something still gets to the terminal and messes with my shell history.
I'm using only 'up arrow' key to go to last entry in shell history. After second execution of 'cb status' it still enters some characters to my shell, and takes my further in my history that I'd like ;)
[Kooha-2023-06-07-15-36-44.webm](https://github.com/Slackadays/Clipboard/assets/6512767/6daafbaf-b830-44b3-b857-1f060689e35f)

**Comment by Slackadays** [comment]
The latest commit should be even better now, so I think this issue is ready to be closed. If you need help with anything else, I'll be there for you!

**Comment by alteriks** [comment]
@Slackadays Thank you so much now it works great!
