### ISSUE TITLE
history.cpp:181:44: warnin g: format specifies type 'size_t' (aka 'unsigned long') but the argument has type 'rep' (aka '__int128')

### ISSUE THREAD

**Issue by happysalada** [Slackadays/Clipboard#128]
**Describe the bug**
This is not a bug, just a warning when compiling version 0.8
```
/tmp/nix-build-clipboard-jh-0.8.0.drv-0/source/src/cb/src/actions/history.cpp:181:44: warnin
g: format specifies type 'size_t' (aka 'unsigned long') but the argument has type 'rep' (aka '__int128') [
-Wformat]
clipboard-jh>         printf("        \"date\": %zu,\n", fs::last_write_time(path.data).time_since_epoch()
.count());
clipboard-jh>
```
I compiled on darwin x86_64

**Version**
0.8.0

**Questionnaire**
Check these boxes to see if your issue is valid or not.
- [X] If I compiled CB, then any errors that may be present don't mention "LTO error" (this is sadly a bug with the compiler, not Clipboard)
- [X] If I compiled CB, then any errors that may be present don't mention "XYZ has not been defined in namespace std" (this sadly means you need a compiler with C++20 support, so upgrade first)
- [ ] I check all these boxes without reading them
- [ ] I think bachata is the best music
- [X] I'm using the latest commit/release (we only support the latest)
- [ ] If I downloaded CB from GitHub Actions or with the install script, any errors that may be present don't mention "GLIBC XYZ not found" (your system is sadly too outdated for CB, so upgrade it)

not a big deal, just thought you might be interested!

**Comment by Slackadays** [comment]
Done, fixed in https://github.com/Slackadays/Clipboard/commit/20590bb3882214cf4cfc29d2d478977ff923ad28

**Comment by happysalada** [comment]
Thank you for the quick response !
