### ISSUE TITLE
when i reboot system , and run cb hs command , the history is blank , is not find.

### ISSUE THREAD

**Issue by newyorkthink** [Slackadays/Clipboard#131]
![image](https://github.com/Slackadays/Clipboard/assets/87791643/335dceeb-bd5b-413a-a8b8-7d530b831197)

i restart system , the history is not show ?

**Comment by Slackadays** [comment]
This is intentional, you have to use a persistent clipboard that starts with `_` to make it work after reboot

**Comment by newyorkthink** [comment]
> This is intentional, you have to use a persistent clipboard that starts with `_` to make it work after reboot

how can use _

**Comment by newyorkthink** [comment]
![image](https://github.com/Slackadays/Clipboard/assets/87791643/d4aecd7c-e0dd-4156-8161-a4a9f9e153a7)

**Comment by Slackadays** [comment]
try `cb copy_ foo` and `cb hs_`

**Comment by newyorkthink** [comment]
> try `cb copy_ foo` and `cb hs_`

but i copy the text in browser ,how can use _

**Comment by Slackadays** [comment]
this feature will be added in a future version

**Comment by newyorkthink** [comment]
![image](https://github.com/Slackadays/Clipboard/assets/87791643/ab3e5521-5c4b-4f67-9bc8-5fd02da73e99)

**Comment by newyorkthink** [comment]
is right?

**Comment by Slackadays** [comment]
that is right, you are looking at the history for clipboard `_`

**Comment by newyorkthink** [comment]
wait mini , i restart system now

**Comment by newyorkthink** [comment]
![image](https://github.com/Slackadays/Clipboard/assets/87791643/095b61d8-6cd8-425e-9309-abc673840c18)

is not show

**Comment by Slackadays** [comment]
did you copy something into `_`?

**Comment by newyorkthink** [comment]
i dont not how to like this:
for example:
i copy "did you copy something into _?" this in browser.
cb hs is can show 
![image](https://github.com/Slackadays/Clipboard/assets/87791643/a5141fc3-043b-470a-8a34-3496a5eb3ef8)


but cb hs_ is not show :
![image](https://github.com/Slackadays/Clipboard/assets/87791643/254c4b7b-11fd-4a89-82ac-f9a68eb45f4b)

**Comment by Slackadays** [comment]
right now if you copy something from the browser, it only goes into clipboard `0`, not `_`

so, you are currently unable to do what you want this way, BUT this will be fixed in 0.8.1
