### ISSUE TITLE
when i use flameshot to take a screenshot , cb is copy, but it cannot paste the github 

### ISSUE THREAD

**Issue by newyorkthink** [Slackadays/Clipboard#132]
![image](https://github.com/Slackadays/Clipboard/assets/87791643/17bc9e8a-9176-4030-9483-d114dc8c7197)

cb is have  me use flameshot screenshot,

but i dont not how to paste the github

**Comment by Slackadays** [comment]
Try Ctrl+V in the text box

**Comment by newyorkthink** [comment]
![image](https://github.com/Slackadays/Clipboard/assets/87791643/639f7b34-8535-4638-9e26-a1214aeebc11)

**Comment by newyorkthink** [comment]
![image](https://github.com/Slackadays/Clipboard/assets/87791643/f63f7c64-4375-48e6-a970-9524e22f66b9)

**Comment by newyorkthink** [comment]
it work

**Comment by newyorkthink** [comment]
![image](https://github.com/Slackadays/Clipboard/assets/87791643/042bc117-ab39-4a87-9da0-e5171360e231)
