### ISSUE TITLE
cb picture cannot paste to vmware 

### ISSUE THREAD

**Issue by newyorkthink** [Slackadays/Clipboard#134]
i copy some picture to test 
![image](https://github.com/Slackadays/Clipboard/assets/87791643/77a33742-934c-43b0-8a24-3358150007ee)

vmware is enable copy and paste
![image](https://github.com/Slackadays/Clipboard/assets/87791643/375c37ec-b8ab-40e0-ae0a-047a995c7b10)

but cb is cannot paste to vmware
![image](https://github.com/Slackadays/Clipboard/assets/87791643/30265307-15db-456b-b60e-4a3a570deb2e)

**Comment by Slackadays** [comment]
@tranzystorek-io How did you get cb working on vmware for you?

**Comment by tranzystorek-io** [comment]
on xorg-based guest environments vmware simply mirrors the clipboard contents between host and guest, but vmware guest tools needs to be properly set up, which varies from system to system

**Comment by Slackadays** [comment]
@newyorkthink Did you install vmware guest tools?

**Comment by newyorkthink** [comment]
> @newyorkthink Did you install vmware guest tools?

yes , i install vm guest tools 
![image](https://github.com/Slackadays/Clipboard/assets/87791643/39b92b49-347d-4c4c-b8ec-34cdcff9d878)

today , i test it

i just restart windows, is ok

![image](https://github.com/Slackadays/Clipboard/assets/87791643/f31c4851-53ab-41d3-a2e8-4ec62e4cceeb)

**Comment by newyorkthink** [comment]
but , it cannot copy to  the folder in windows guest 
![image](https://github.com/Slackadays/Clipboard/assets/87791643/1e88008b-2896-488c-bbee-0aeae6b14dff)
![image](https://github.com/Slackadays/Clipboard/assets/87791643/7cf1da23-7328-480a-8ee4-a0bedb749c56)

**Comment by supsm** [comment]
That should be pretty obvious. The guest has no idea about anything in the host filesystem, and additionally the clipboard formats for files on linux and windows are different. I'm pretty sure that the only way you can transfer files to/from a virtual machine is through the vmware drag and drop feature.
