### ISSUE TITLE
cb add fzf

### ISSUE THREAD

**Issue by newyorkthink** [Slackadays/Clipboard#137]
fzf is dynamaic search

use cb + fzf is nice

like mcfly command

**Comment by Slackadays** [comment]
try this to copy text into cb:

```sh
$ fzf | cb
```

try this to copy a file into cb:

```sh
$ cb copy $(fzf)
```

**Comment by newyorkthink** [comment]
I mean is not like this.

Is fzf into cb , 
Look like mcfly command
Is my suggestion

**Comment by Slackadays** [comment]
Added something very similar in https://github.com/Slackadays/Clipboard/commit/eaf93969096a197d3972db99ca0d4c6dadde47a1
