### ISSUE TITLE
the libgui.a file is save to /usr/lib , is hare path?

### ISSUE THREAD

**Issue by newyorkthink** [Slackadays/Clipboard#145]
![image](https://github.com/Slackadays/Clipboard/assets/87791643/e85ceb3c-d8f6-41b0-9d6a-29deb0acbf77)

is right?

**Comment by Slackadays** [comment]
which OS do you use? this should not happen, unless your OS is a special case, and then I can't fix this

**Comment by newyorkthink** [comment]
> which OS do you use? this should not happen, unless your OS is a special case, and then I can't fix this您使用哪种操作系统？这不应该发生，除非您的操作系统是特例，然后我无法解决此问题

my os ,is debian likely

**Comment by Slackadays** [comment]
how did you install `cb`?

**Comment by newyorkthink** [comment]
> how did you install `cb`?

i use you binary file , i link cb to /usr/bin/
and copy three lib file to /usr/lib
just it

**Comment by newyorkthink** [comment]
i download you binary file ,and link cb to /usr/bin/

and copy three lib file to /usr/lib/ 
just it

**Comment by Slackadays** [comment]
then, you do not need `libgui.a`, because that is only needed to compile the `cb` binary

**Comment by newyorkthink** [comment]
> then, you do not need `libgui.a`, because that is only needed to compile the `cb` binary然后，你不需要 `libgui.a` ，因为它只需要编译 `cb` 二进制文件

ok
