### ISSUE TITLE
How to use `cb paste` to paste in the terminal

### ISSUE THREAD

**Issue by jetm** [Slackadays/Clipboard#146]
I want to use `cb` as a replacement for `xsel` and `xclip`. I figured out `cb paste 2> /dev/null | cat -` paste text in the terminal, but I found that syntax a bit clunky and difficult to remember. Is there a better way to do it using only `cb` arguments, like `xsel --output --clipboard` does.

**Comment by jetm** [comment]
No, it doesn't work.  The first `cb | cat` fails with this error:
```
$ terminate called after throwing an instance of 'X11Exception'
  what():  Tried to call XChangeWindowAttributes while a call to XNextEvent was already in progress
terminate called after throwing an instance of 'X11Exception'                                          
```

With `-nc` stills show a message and nor doesn't work:
```
$ cb -nc | cat -               
 ✔  Pasted 19B                                                                                         
```

Using `Clipboard Project 0.8.1 (commit 53f55a0)`

**Comment by Slackadays** [comment]
the `cb | cat` error looks like something is broken with X11. what OS are you using?

for `-nc`, I just tried this and it showed the message still, so this is a bug that should be fixed very soon :)

**Comment by jetm** [comment]
I am using Linux:
```
Kernel: 6.1.38-1-MANJARO arch: x86_64 bits: 64
Desktop: KDE Plasma v: 5.27.6 Distro: Manjaro Linux
Display: x11 server: X.Org v: 21.1.8
```

**Comment by Slackadays** [comment]
fixed confirmation issue in https://github.com/Slackadays/Clipboard/commit/ef7edab6630c0fced6d47527a70e56eab2a47494

**Comment by jetm** [comment]
@Slackadays Thank you for the fix. I am not seeing the failure anymore when running `cb -nc | cat -`. Still, it shows text with `-nc` flags. I dunno if that is expected, but it would be nice to have a `quiet` flag to only see the copied data and not use `2>/dev/null`.

See the case:
```
❯ echo "text copied" | ./cb copy
 ✔  Copied 12B                                                                                                                                                              
❯ ./cb -nc | cat -              
⬤ Setting up... %?, 0s elapsed █▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒    text copied                                                                                                                                                                                   
❯ ./cb -nc 2> /dev/null | cat -
text copied
```
Version:
```
This is the Clipboard Project 0.8.1 (commit ef7edab), the cut, copy, and paste system for the command line.
```

**Comment by Slackadays** [comment]
You can do `export CLIPBOARD_SILENT=1` to just disable everything at once, would that work?

**Comment by jetm** [comment]
`CLIPBOARD_SILENT=1` works. Thanks! I believe a flag would be better; a flag is faster to type. But the environment variable works. You might want to close this issue. Thank you for everything!

**Comment by Slackadays** [comment]
I'm always here to help! :)
