### ISSUE TITLE
Feature Request: standards compliant usage syntax in help text

### ISSUE THREAD

**Issue by sparr** [Slackadays/Clipboard#15]
**Is your feature request related to a problem? Please describe.**
The usage definition and examples in the help text and README are unhelpfully freeform. There is ambiguousness and un-covered cases in each of them.

**Describe the solution you'd like**
Add http://docopt.org/ compliant* usage help, in the program and in the README. This could replace a bit of the existing documentation, but most of the longer descriptive examples and explanations could still work alongside this.

It might look something like this:
```
Usage:
  clipboard copy(n) [FILE ...]
  clipboard cut(n) [FILE ...]
  clipboard paste(n)
  clipboard show(n)
  clipboard clear(n)
  clipboard
```

This doesn't require actually using docopt.cpp to parse the help text or options.

\* the `copy1` syntax might not be possible to make fully compliant, but I'll be opening another issue for that.

**Comment by Slackadays** [comment]
Won't Fix: Clipboard intentionally breaks the rules here because newbie users might not be able to understand the "correct" syntax but have a higher chance of understanding the Broke The Rules one.

**Comment by sparr** [comment]
You're ignoring newbie users who are going to do `clipboard [tab key]` and hope for completion suggestions :(

I'm not saying the "broke the rules" explanation needs to go away. A standard help text or man page implementation can have an examples section which could contain almost all the stuff you're referring to.
