### ISSUE TITLE
Invalid JSON output

### ISSUE THREAD

**Issue by useredsa** [Slackadays/Clipboard#152]
**Describe the bug**

The output of `cb info` is not valid JSON. It lacks a comma after the filed note. Thus, it cannot be piped to other tools.

Some other commands, like `cb history` and `cb search` also suffer from a similar problem. In these cases because clipboard does not escape some characters properly.

**Example**

```json
~$ info -c kak | cat
{                                                                                      
    "name": "kak",
    "created": "Thu Jul 27 13:38:54 2023",
    "lastChanged": "Thu Jul 27 13:38:54 2023",
    "path": "/run/user/1000/Clipboard/kak",
    "owner": "useredsa",
    "isPersistent": false,
    "totalEntries": 2,
    "totalBytesUsed": 301,
    "totalBytesRemaining": 1643655168,
    "contentBytes": 1,
    "contentType": "text/plain",
    "contentCut": false,
    "locked": false,
    "note": "" <- HERE
    "ignoreRegexes": []
}
```

```sh
~ $ cb history 2> /dev/null | jq
parse error: Invalid characters in \uXXXX escape at line 780, column 210
```

Line 780:
```
778|    "191": {
779|        "date": 13699534026133701064,
780|        "content": "\uff,fff,fe2\uff,fff,f9c\uff,fff,f98  You can't load a clipboard into itself. \uff,fff,fe2\uff,fff,fac\uff,fff,fa4 Try choosing a different source instead, or choose different destinations."
781|    },
```

**Version**

I am using version 0.8.1, obtained from the Arch User Repositories, but the current latest commit also has the same problem.

**Questionnaire**
Check these boxes to see if your issue is valid or not.
- [x] If I compiled CB, then any errors that may be present don't mention "LTO error" (this is sadly a bug with the compiler, not Clipboard)
- [x] If I compiled CB, then any errors that may be present don't mention "XYZ has not been defined in namespace std" (this sadly means you need a compiler with C++20 support, so upgrade first)
- [ ] I check all these boxes without reading them
- [ ] I think bachata is the best music
- [x] I'm using the latest commit/release (we only support the latest)
- [x] If I downloaded CB from GitHub Actions or with the install script, any errors that may be present don't mention "GLIBC XYZ not found" (your system is sadly too outdated for CB, so upgrade it)

**Comment by RuiNtD** [comment]
On Windows, the path is also not escaped.
```json
{
          "name": "0",
    "created": "n/a",
    "lastChanged": "2023-08-04 20:17:31.4240258",
    "path": "C:\Users\ethan\AppData\Local\Temp\Clipboard\0",
    "owner": "n/a",
    "isPersistent": false,
    "totalEntries": 15,
    "totalBytesUsed": 138972,
    "totalBytesRemaining": 505415942144,
    "contentBytes": 15,
    "contentType": "text/plain",
    "contentCut": false,
    "locked": false,
    "note": ""
    "ignoreRegexes": []
}
```
Same applies for `cb history`:
```json
{
    "13": {
        "date": 133356876486386815,
        "content": [
            {
                "filename": "files.json",
                "path": "C:\Users\ethan\AppData\Local\Temp\Clipboard\0\data\3\files.json",
                "isDirectory": false
            }

        ]
    }
}
```

**Comment by Slackadays** [comment]
Please see the following for why Windows has issues like these:
![xzqfmjhd04gb1](https://github.com/Slackadays/Clipboard/assets/69403549/5749bba7-a8de-41fe-82d9-2f36e595e2ed)

**Comment by useredsa** [comment]
@Slackadays you can consider using/taking the encoder from a Json library like nlohmann/json.cpp. The issues are not related to Linux or Windows I believe.

**Comment by Slackadays** [comment]
fixed in https://github.com/Slackadays/Clipboard/commit/7c264bbd46775624c9a57d1e94d677043292a343
