### ISSUE TITLE
Date of last change is updated on paste.

### ISSUE THREAD

**Issue by useredsa** [Slackadays/Clipboard#153]
**Describe the bug**

Clipboard does not (currently) have a daemon, so it copies the system's clipboard (Xorg or Wayland) to clipboard 0 everytime you execute `cb paste` or `cb`. However, this updates the modification time of the clipboard even if the contents stay the same. What is worse, executing `cb` updates the modification time of all clipboards, not only clipboard 0.

**To Reproduce**
1. Copy the text "text 0" to the clipboard and execute `cb`. (You'll see it in clipboard 0.)
2. Execute `cb info -c 0` and annotate the date.
3. Execute `cb paste -c 0 2> /dev/null | cat`, but don't copy anything into the system's clipboard.
4. Execute `cb info -c 0` again. The dates differ.

To reproduce the problem with the other clipboards:
1. Execute `echo text 0 | cb copy0 ; echo text 1 | cb copy1`.
2. Execute `cb info -c 1` and annotate the date (it will be the current moment).
3. Execute `cb`. The contents of both clipbards are "text 0" and "text 1".
4. Execute `cb info -c 1`. The new date is different.

**Expected behavior**

In both cases, the dates should have stayed the same. The modification date should only change when we execute `cb copy`. For clipboard 0, which is special, the modification date should also change if, after probing the system's clipboard, we see that its contents have been updated since the last time we probed.

Currently, comparing the modification dates of the different clipboards to know which one is newer is most of the time incorrect.

**Version**

Version 0.8.1 obtained from Arch User repositories. Same thing applies in currently latest commit.

**Comment by Slackadays** [comment]
fixed in https://github.com/Slackadays/Clipboard/commit/26a0c64ef44356711b759a48c798788559a6d47e
