### ISSUE TITLE
zsh completion

### ISSUE THREAD

**Issue by bbhtt** [Slackadays/Clipboard#155]
**Describe the bug**

Autocompletion seems to now work with zsh but works with bash

**To Reproduce**

Steps to reproduce the behaviour:

1. `touch test`
2. Enter `cb copy t...` and start pressing tab
3. `test` does not complete

**Expected behaviour**

Autocomplete should work

**Screenshots**

[20d23a1caf.webm](https://github.com/Slackadays/Clipboard/assets/62639087/8c0fddbc-f8d1-4edf-91ee-683b493e1b11)

**Version**

0.8.1 (commit 263df73), Flathub on Fedora 38

**Questionnaire**
Check these boxes to see if your issue is valid or not.
- [ ] If I compiled CB, then any errors that may be present don't mention "LTO error" (this is sadly a bug with the compiler, not Clipboard)
- [ ] If I compiled CB, then any errors that may be present don't mention "XYZ has not been defined in namespace std" (this sadly means you need a compiler with C++20 support, so upgrade first)
- [ ] I check all these boxes without reading them
- [ ] I think bachata is the best music
- [x] I'm using the latest commit/release (we only support the latest)
- [ ] If I downloaded CB from GitHub Actions or with the install script, any errors that may be present don't mention "GLIBC XYZ not found" (your system is sadly too outdated for CB, so upgrade it)

**Additional context**

I assume the program needs to provide the autocompletion. Seems like currently only bash and fish are provided. In that case having something for zsh would be appreciated.

**Before you post**
Please make sure you check previous bug reports before filing a new one.
This will help keep the Issues section less cluttered. :)
Feel free to delete this section once you've completed this form.

**Comment by Slackadays** [comment]
added in https://github.com/Slackadays/Clipboard/commit/8d76ee0c2102ec2b29beb37a4072303005665f24
