### ISSUE TITLE
Segmentation Fault with `cb -c`

### ISSUE THREAD

**Issue by cscherrNT** [Slackadays/Clipboard#156]
**Describe the bug**
When using `cb -c` or `cb --clipboard`, the program generates a segementation fault.

```
❯ cb --clipboard
zsh: segmentation fault  cb --clipboard
```

**To Reproduce**
1. Download latest GitHub Release and unzip it
2. install the bin to `/usr/local/bin/cb`, the libs to `/usr/local/lib`
3. `sudo chmod +x /usr/local/bin/cb`
4. `sudo chown root:root /usr/local/bin/cb`
5. `sudo chown root:root /usr/local/lib/*`
6. Use command `cb -c` or `cb --clipboard`

**Expected behavior**
[see clipboard flag](https://getclipboard.app/docs/#flags)
Print a help section if the input is bad.

**Screenshots**
Not appliciable

**Version**
 Clipboard Project 0.8.1 (commit 263df73), just now downloaded from the latest GitHub Release.
OS is Debian 12, with kernel 6.1.0-10-amd64

**Questionnaire**
Check these boxes to see if your issue is valid or not.
- [X] If I compiled CB, then any errors that may be present don't mention "LTO error" (this is sadly a bug with the compiler, not Clipboard)
- [X] If I compiled CB, then any errors that may be present don't mention "XYZ has not been defined in namespace std" (this sadly means you need a compiler with C++20 support, so upgrade first)
- [ ] I check all these boxes without reading them
- [ ] I think bachata is the best music
- [X] I'm using the latest commit/release (we only support the latest)
- [x] If I downloaded CB from GitHub Actions or with the install script, any errors that may be present don't mention "GLIBC XYZ not found" (your system is sadly too outdated for CB, so upgrade it)

**Additional context**
The Machine this occurs on is a Virtual Machine, running on Windows 11 with Oracle VirtualBox as Hypervisor. copying with `cb` does not copy to the host clip board (copying to clipboard in neovim does). I'm using XFCE for my Desktop Environment, with X11.

If I append a value after `cb -c` like this: `cb -c foo`, no segfault occurs.

This also occurs when installing `cb` with `curl -sSL https://github.com/Slackadays/Clipboard/raw/main/install.sh | sh`

**Comment by Slackadays** [comment]
fixed in https://github.com/Slackadays/Clipboard/commit/c78f98e06279fbd779f128176999cd6f09f9f1a2
