### ISSUE TITLE
Keeps copying text only

### ISSUE THREAD

**Issue by farzadmf** [Slackadays/Clipboard#158]
**Describe the bug**
I'm inside a directory with two sub-directories `public` and `src`. I want to copy those as directories to be able to paste them, but `clipboard` keeps copying them as text.

**To Reproduce**
1. Go to a directory with sub-directories (example: `public` and `src`)
![image](https://github.com/Slackadays/Clipboard/assets/5768792/e2df3120-cbc6-4eec-ba35-6d87085748d6)
2. Try to copy the sub-dirs: `cp cp_1 public src`
3. See the text "public src" being copied
![image](https://github.com/Slackadays/Clipboard/assets/5768792/188cad6b-9961-4574-81ae-b4eea9579c40)

**Expected behavior**
I expect the two directories to be copied as directories and not their names as text

**Screenshots**
Plase see above

**Version**
Clipboard Project 0.8.1 (commit 263df73) (Flatpak version) on Amazon Linux

**Questionnaire**
Check these boxes to see if your issue is valid or not.
- [x] If I compiled CB, then any errors that may be present don't mention "LTO error" (this is sadly a bug with the compiler, not Clipboard)
- [x] If I compiled CB, then any errors that may be present don't mention "XYZ has not been defined in namespace std" (this sadly means you need a compiler with C++20 support, so upgrade first)
- [x] I check all these boxes without reading them
- [x] I think bachata is the best music
- [x] I'm using the latest commit/release (we only support the latest)
- [x] If I downloaded CB from GitHub Actions or with the install script, any errors that may be present don't mention "GLIBC XYZ not found" (your system is sadly too outdated for CB, so upgrade it)

**Additional context**
I think (not sure TBH) that it was working fine before

**Comment by Slackadays** [comment]
What permissions do you have enabled in Flatpak for CB? Because it will copy the items as text if it can't find them as files, which is possible with Flatpak if the permissions are not enabled. Try `flatpak info --show-permissions app.getclipboard.Clipboard` to show them. If you get something like

```
$ flatpak info --show-permissions app.getclipboard.Clipboard
[Context]
shared=ipc;
sockets=x11;wayland;pulseaudio;fallback-x11;
filesystems=xdg-run/Clipboard;host;
```

then the directory you're accessing may not be present in your /home/ directory.

**Comment by farzadmf** [comment]
Yeah, I seem to be getting the same thing:
```
❯ flatpak info --show-permissions app.getclipboard.Clipboard

[Context]
shared=ipc;
sockets=x11;wayland;pulseaudio;fallback-x11;
filesystems=host;xdg-run/Clipboard;
```

> if you need to copy stuff outside of /home/, then you may be out of luck as Flatpak lacks good support for accessing files outside of there

Oh wow, really? that's a shame :pensive:

**Comment by Slackadays** [comment]
Closing this because this is an issue with all Flatpaks, because the Flatpak runtime redirects all accesses to various root directories.

**Comment by farzadmf** [comment]
@Slackadays just to confirm: is the Flatpak able to work with files under `$HOME` and all its subdirectories, or it's only the ones directly under `$HOME`?

**Comment by Slackadays** [comment]
According to the [Flatpak permissions guide](https://docs.flatpak.org/en/latest/sandbox-permissions.html), the `host` filesystem permission gives access to everything except `/lib, /lib32, /lib64, /bin, /sbin, /usr, /boot, /root, /tmp, /etc, /app, /run, /proc, /sys, /dev, /var`. Therefore, it should work just fine for anything in `$HOME` including subdirectories.
