### ISSUE TITLE
Feature Request: standards compliant command line parameter syntax

### ISSUE THREAD

**Issue by sparr** [Slackadays/Clipboard#16]
**Is your feature request related to a problem? Please describe.**
The `copy1` / `paste4` etc syntax  makes clipboard incompatible with tools that automatically handle command line parameters for other tools, such as https://github.com/nevesnunes/sh-manpage-completions

**Describe the solution you'd like**
Add an optional syntax to specify the clipboard number as a named parameter.

`clipboard cut1 somefile` could instead be `clipboard cut -n 1 somefile` or `clipboard cut --clipboard-number=1 somefile`

PS: It would be even better if this was the only syntax, and the user could implement shortcut aliases themself if they want them, but I suspect from the motivations described in the README that such a suggestion would get much less traction, so I've written this as a request for an option.

**Comment by Slackadays** [comment]
Clipboard intentionally breaks the rules here, so changing this syntax to only be the other option would make Clipboard worse. However, I'm open to adding a different supported syntax, but what would you do if you needed to copy a file with name "-c"?

**Comment by sparr** [comment]
The standard solution is to have a parameter named `--` which stops parsing of later dashes as options and treats them as literal strings. So `clipboard copy -c 1 -- -c` would copy the file named `-c` to clipboard #1 (if `-c` specifies the clipboard number).

https://unix.stackexchange.com/questions/11376/what-does-double-dash-mean

**Comment by Slackadays** [comment]
Done, added in latest commit https://github.com/Slackadays/Clipboard/commit/f9e83ed3cb8b85ad56f32cf3040b3fac7eac5e6d and we don't have to check for `--` because Clipboard's current code will only check for the `-c` or `--clipboard=` once.

**Comment by sparr** [comment]
Does that mean that you have to specify `-c 1 -c 1` to copy files named `-c` and `1`?

**Comment by Slackadays** [comment]
That's one way you could do it, or just `1 -c` since the current logic only checks the third argument for the presence of `-c` (the first being `clipboard`, the second `(action)` and the third `1`)
