### ISSUE TITLE
v0.8.2 how to select item

### ISSUE THREAD

**Issue by newyorkthink** [Slackadays/Clipboard#162]
![image](https://github.com/Slackadays/Clipboard/assets/87791643/bc50d638-55f4-4444-bde1-1eb3993255e8)

when use cb 1 command
it cannot select item

i use v0.8.1 ,it just input eg;cb 2
its can select the second item. but v0.8.2 not work

**Comment by Slackadays** [comment]
Use `cb p0-1` to select history item 1 from clipboard 0, `cb 1` never should work

**Comment by newyorkthink** [comment]
> Use `cb p0-1` to select history item 1 from clipboard 0, `cb 1` never should work

sorry , i  forget command 
![image](https://github.com/Slackadays/Clipboard/assets/87791643/16659529-463c-4e1a-bfc7-e0bcf765589e)

is cb hs 1
