### ISSUE TITLE
Strip / Escape new lines when displaying info

### ISSUE THREAD

**Issue by RuiNtD** [Slackadays/Clipboard#165]
**Is your feature request related to a problem? Please describe.**
New lines mess up the formatting of `cb history` when not piped.

**Describe the solution you'd like**
Either remove new lines (`\r?\n`) or replace them with something like `\n` or `⏎` in all commands when not piped (human readable output).
It may also be a good idea to strip ANSI codes.

**Describe alternatives you've considered**

**Additional context**
```
cb history
```
![image](https://github.com/Slackadays/Clipboard/assets/1149870/96ddaf68-3751-4a60-8a19-96f12f01f239)

**Comment by Slackadays** [comment]
Added in https://github.com/Slackadays/Clipboard/commit/883a63a3a3bc9d268e0d092421cdc7f04bdf40d0
