### ISSUE TITLE
Version 0.8.2 fails to build for Homebrew

### ISSUE THREAD

**Issue by nevack** [Slackadays/Clipboard#166]
PR: https://github.com/Homebrew/homebrew-core/pull/148588

CI Check: https://github.com/Homebrew/homebrew-core/actions/runs/6372644141/job/17295629862?pr=148588#step:3:124

Maybe it's because `<algorithm>` is not included in https://github.com/Slackadays/Clipboard/blob/main/src/cb/src/clipboard.hpp ?

**Comment by Slackadays** [comment]
Unfortunately, this is likely inactionable on my end because I can't just add that header, it would require a new release too. However, would it possible for homebrew to apply a patch?

**Comment by Slackadays** [comment]
Actually, it might be best if I made such new release, since that gives me the opportunity to work on #165

**Comment by Slackadays** [comment]
Fixed in https://github.com/Slackadays/Clipboard/commit/883a63a3a3bc9d268e0d092421cdc7f04bdf40d0

**Comment by p-linnane** [comment]
For future reference, we can accept patches in Homebrew.
