### ISSUE TITLE
Feature Request: man page

### ISSUE THREAD

**Issue by sparr** [Slackadays/Clipboard#17]
**Is your feature request related to a problem? Please describe.**
clipboard's documentation isn't accessible in standard ways

**Describe the solution you'd like**
Add a [man page](https://www.zdnet.com/article/what-are-man-pages-and-why-are-they-important-to-your-linux-education/) (or, if necessary, an [info page](https://www.gnu.org/software/texinfo/))

**Additional context**
If there was a man page (in a standard format), it would be machine readable for tools like https://github.com/nevesnunes/sh-manpage-completions, improving usability for power users and folks with advanced shells and other tools.

**Comment by Slackadays** [comment]
Added in latest commit https://github.com/Slackadays/Clipboard/commit/ad26acbfb38df4ed488bc7dde1dae69056cd9147, uses markdown but has a roff version from Pandoc
