### ISSUE TITLE
Bug: `CI` environment variable undocumented, silently forces overwrite

### ISSUE THREAD

**Issue by sparr** [Slackadays/Clipboard#18]
**Describe the bug**
Having an env variable named `CI` triggers the no-tty behaviors in clipboard, which forces overwrite of files

**To Reproduce**
1. `touch foo`
2. `clipboard copy foo`
3. `CI=something clipboard paste`

**Expected behavior**
overwrite prompt, or default to not overwrite without an option like `-f` or `--force`, or the CI env behavior documented in the readme, help text, and/or man page.

**Comment by Slackadays** [comment]
Add in latest commit https://github.com/Slackadays/Clipboard/commit/ad26acbfb38df4ed488bc7dde1dae69056cd9147, now in readme, help message, and man page
