### ISSUE TITLE
Persistent directory bug

### ISSUE THREAD

**Issue by vaskark** [Slackadays/Clipboard#181]
A bug in the persistent directory config.

cb config:

`Persistent directory: /home/$USER/.local/state/.local/state/clipboard
`

Expected:

`Persistent directory: /home/$USER/.local/state/clipboard
`

Clipboard 0.9.0 on Ubuntu 23.10 (amd64)
XDG_STATE_HOME="$HOME/.local/state"

Thank you. It's a great app. Keep up the great work.

**Comment by Slackadays** [comment]
Fixed in https://github.com/Slackadays/Clipboard/commit/9af03b2302c6d38c8bbe728b8d3c8c2959535727, will re-do 0.9.0 with this quick fix
