### ISSUE TITLE
GUI integration coredumps after some time

### ISSUE THREAD

**Issue by dgudim** [Slackadays/Clipboard#188]
**Describe the bug**

After about 30 minutes after last using clipboard, its gui daemon crashes
```
[🡕] Process 27496 (cb) of user 1000 dumped core.
                                                              
                                                              Stack trace of thread 27496:
                                                              #0  0x000071f48ccf43d6 readdir64 (libc.so.6 + 0xd63d6)
                                                              #1  0x000058e61880cfca _ZN9Clipboard19generatedEntryIndexEv (cb + 0x1ffca)
                                                              #2  0x000058e618810e7d _ZN9ClipboardC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKm (cb + 0x23e7d)
                                                              #3  0x000058e618826a71 _Z23setupGUIClipboardDaemonv (cb + 0x39a71)
                                                              #4  0x000058e6188068e5 main (cb + 0x198e5)
                                                              #5  0x000071f48cc45cd0 n/a (libc.so.6 + 0x27cd0)
                                                              #6  0x000071f48cc45d8a __libc_start_main (libc.so.6 + 0x27d8a)
                                                              #7  0x000058e61880ab15 _start (cb + 0x1db15)
                                                              ELF object binary architecture: AMD x86-64
```

**To Reproduce**
1. Type cb
2. Wait

**Expected behavior**
Nothing crashes

**Version**
I'm using CB 0.9.0 from the Arch repos

**Questionnaire**
Check these boxes to see if your issue is valid or not.
- [ ] If I compiled CB, then any errors that may be present don't mention "LTO error" (this is sadly a bug with the compiler, not Clipboard)
- [ ] If I compiled CB, then any errors that may be present don't mention "XYZ has not been defined in namespace std" (this sadly means you need a compiler with C++20 support, so upgrade first)
- [ ] I check all these boxes without reading them
- [x] I think ~~bachata~~ DnB is the best music
- [ ] I'm using the latest commit/release (we only support the latest)
- [ ] If I downloaded CB from GitHub Actions or with the install script, any errors that may be present don't mention "GLIBC XYZ not found" (your system is sadly too outdated for CB, so upgrade it)

**Comment by segln** [comment]
Same issue on Arch linux ARM.

6.9.10-1-aarch64-ARCH
cb 0.8.2 (commit 9dff27c)

**Comment by Slackadays** [comment]
@dgudim Looks like this might actually be a libc issue since the stacktrace puts the issue there. Does it still happen all these months later?

**Comment by dgudim** [comment]
Does not look like it, this can be closed then
