### ISSUE TITLE
Feature Request: symlink option when copying files

### ISSUE THREAD

**Issue by sparr** [Slackadays/Clipboard#19]
When copying a file, the file is literally copied to the clipboard tmp (or non-tmp) directory. This could be slow for big files, or have other drawbacks in certain situations. I'd like an option that would result in a symlink being made instead of a copy. Just for the tmp dir; paste would still copy the file.

A down side of this would be that paste would reflect any changes made to the file on disk after it was copied. This should be documented. It could also result in a notification to the user when they try to paste, if the modification time on the file is newer than the creation time on the symlink.

**Comment by Slackadays** [comment]
Clipboard already transparently uses hard links by default, so in the best case, no actual copying happens. However, I'm also scared of users modifying files only to find out they can't just paste the old versions, so maybe I can add an option to use regular copying instead.

**Comment by Slackadays** [comment]
Done, added in https://github.com/Slackadays/Clipboard/commit/8e452385759aa3cff628a44794d0c0ed67902fc4, also along with proper `--` compat
