### ISSUE TITLE
Parsing json unicode characters

### ISSUE THREAD

**Issue by Bellavene** [Slackadays/Clipboard#195]
I have this working code to view clipboard history through fzf
`cb hs | jq --raw-output0 '.[].content | select(type=="string")' | fzf --read0 --ansi --bind 'enter:execute-silent(cb copy "$(echo {})")+abort' --bind 'alt-r:reload(pasteboard-history)'`

But it screws up unicode characters
`￿ffd0￿ff9f￿ffd1￿ff80￿ffd0￿ffb8￿ffd0￿ffb2￿ffd0￿ffb5￿ffd1￿ff82`

Is it possible, so `cb hs` will pipe out the content right and so it would not be detected as binary, therefore there will be no need to use raw output while piping?

**Comment by Slackadays** [comment]
Unicode escaping is hard, what characters in particular did you copy?

**Comment by Slackadays** [comment]
Fixed in https://github.com/Slackadays/Clipboard/commit/802fd60b2eff0d0c7f0f1212030d346b364dd4de
