### ISSUE TITLE
Windows installation fails

### ISSUE THREAD

**Issue by Kurren123** [Slackadays/Clipboard#198]
**Describe the bug**
The windows installation is failing with the following error:

```
Invoke-WebRequest : Error 404 – Not Found
GitHub produced an error for the download of artifact #1119605681.
Usually this means that the artifact has expired (>90 days).
Check on GitHub: https://github.com/Slackadays/Clipboard/suites/19111531853/artifacts/1119605681
Return to the home page
At line:1 char:1
+ Invoke-WebRequest https://nightly.link/Slackadays/Clipboard/workflows ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**To Reproduce**
Run `(Invoke-WebRequest -UseBasicParsing https://github.com/Slackadays/Clipboard/raw/main/install.ps1).Content | powershell`

**Expected behavior**
Should install without errors

**Questionnaire**
Check these boxes to see if your issue is valid or not.
- [ ] I check all these boxes without reading them
- [x] I think bachata is the best music
- [x] I'm using the latest commit/release (we only support the latest)

**Additional context**
I'm on windows 11

**Comment by Kurren123** [comment]
May I suggest instead of downloading the github artifact, which expires, we publish to winget? I can work on this if you're happy with this plan.

**Comment by Slackadays** [comment]
@Kurren123 I would love to get CB on winget, are you still able to help?

**Comment by Slackadays** [comment]
@bevsxyz, @steveatthru, since you are interested in this too, would you also like to try giving Winget a shot?

**Comment by bevsxyz** [comment]
I made a pull request.

https://github.com/microsoft/winget-pkgs/pull/184692

**Comment by Slackadays** [comment]
The original issue has been fixed in https://github.com/Slackadays/Clipboard/commit/d89fcbbf8d37a010d6750d0303a1ac6231db68bf, I have no clue what I was thinking to link to nightly instead of the latest release
