### ISSUE TITLE
Problem cutting file

### ISSUE THREAD

**Issue by nivaca** [Slackadays/Clipboard#2]
Hi, I get the following error when cutting a file:

```
~/Downloads 
 ⟩ cd ~/Downloads/
~/Downloads 
 ⟩ touch test.txt
~/Downloads 
 ⟩ clipboard cut test.txt
╳ Clipboard couldn't cut these items:
▏ test.txt: Invalid cross-device link
▏ See if you have the needed permissions, or
▏ try double-checking the spelling of the files or what directory you're in.
```

I have the permissions for the file:

```
 ⟩ ls -l test.txt
.rw-r--r--. nivaca 0B 10 Dec 22 16:57:44 test.txt
~/Downloads 
 ⟩ rm test.txt
~/Downloads 
```

I'm on Fedora 37:

```
 ⟩ uname -a
Linux nivaca-pc 6.0.10-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Nov 26 16:55:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Copy/paste does work, however.

Any ideas?

**Comment by Slackadays** [comment]
The `cut` action uses the `rename` syscall internally. However, this syscall won't work if the target and destination are in separate filesystems, which looks to be the case for you. The fix for this will be to replace the `cut` implementation with what `copy` uses but also delete the original files after. 

Check this out: https://stackoverflow.com/questions/42392600/oserror-errno-18-invalid-cross-device-link

**Comment by nivaca** [comment]
Indeed, the temp folder that is created (in /tmp/Clipboard/) is in another disk.  That's really a problem, since I always separate in different disks my personal files from the system's (including those in /tmp).

**Comment by Slackadays** [comment]
Unfortunately, while fixing the cut issue itself will be a quick fix, I don't think it might be as easy to make a fix for a custom temporary directory. Would putting the preferred directory in the environment variable TMPDIR work? This seems to be the standard across all the platforms.

**Comment by nivaca** [comment]
No, unfortunately it won't.  Nevermind.

**Comment by Slackadays** [comment]
I've just reopened this issue because although a custom temporary directory might not be a necessity right now, the cut action still fails to account for platforms with different filesystems.

**Comment by Slackadays** [comment]
Check out this latest commit with the quick fix. As a bonus, Clipboard is now several hundred bytes smaller in size. https://github.com/Slackadays/Clipboard/commit/fd51ba9adcec2055e790216e77dad0aca40e65cf

**Comment by Slackadays** [comment]
Closing because copying the file across filesystems works, while the old method didn't.
