### ISSUE TITLE
Bug: several errors in the C++ source file clipboard.cpp 

### ISSUE THREAD

**Issue by miguelgargallo** [Slackadays/Clipboard#20]
**Describe the bug**
After clean install, it fails on build

**To Reproduce**
1. cmake --build .

**Expected behavior**
Use Clipboard

**Screenshots**
![image](https://user-images.githubusercontent.com/5947268/209657519-16962f9c-b51e-4590-b805-ad9eb890dcfa.png)

**Additional context**
chatGPT:
Pencil Originals
Explain on a text, that error while I was trying to install Clipboard from github on my Ubuntu 20.04.5 LTS

here is the error

ANSWER:
It looks like there are several errors in the C++ source file clipboard.cpp while trying to build the Clipboard project on your Ubuntu 20.04.5 LTS system.

Here is a summary of the errors:

    ‘jthread’ in namespace ‘std’ does not name a type; did you mean ‘thread’? - This error is occurring at line 51 and it suggests that the identifier jthread is not a recognized type in the std namespace. Instead, it is suggesting that you might have meant to use the thread type.

    ‘indicator’ was not declared in this scope - This error is occurring at lines 182, 503, 637, and 778. It means that the indicator variable has not been declared or is not in scope at the location where it is being used.

    variable or field ‘setupIndicato’ declared void - This error is occurring at line 432 and it means that the setupIndicato variable or field has been declared as having the void type, which is not valid.

    ‘stop_token’ is not a member of ‘std’ - This error is occurring at line 432 and it means that the stop_token type is not a member of the std namespace.

    ‘jthread’ is not a member of ‘std’; did you mean ‘thread’? - This error is occurring at lines 639 and 778 and it means that the jthread type is not a member of the std namespace. It is suggesting that you might have meant to use the thread type instead.

    ‘setupIndicator’ was not declared in this scope - This error is occurring at lines 639, 778, and 778 and it means that the setupIndicator identifier has not been declared or is not in scope at the location where it is being used.

To fix these errors, you will need to review the clipboard.cpp file and make sure that all variables and types are properly declared and in scope, and that you are using the correct types and identifiers. You may also need to check that you have the necessary dependencies and libraries installed on your system in order to build the project successfully.

```
user@computer:~/hello$ cmake --build .
[ 50%] Building CXX object CMakeFiles/clipboard.dir/src/clipboard.cpp.o
/home/and/hello/Clipboard/src/clipboard.cpp:51:6: error: ‘jthread’ in namespace ‘std’ does not name a type; did you mean ‘thread’?
   51 | std::jthread indicator;
      |      ^~~~~~~
      |      thread
/home/and/hello/Clipboard/src/clipboard.cpp: In lambda function:
/home/and/hello/Clipboard/src/clipboard.cpp:182:9: error: ‘indicator’ was not declared in this scope
  182 |         indicator.request_stop();
      |         ^~~~~~~~~
/home/and/hello/Clipboard/src/clipboard.cpp: At global scope:
/home/and/hello/Clipboard/src/clipboard.cpp:432:26: error: variable or field ‘setupIndicato
’ declared void
  432 | void setupIndicator(std::stop_token st) {
      |                          ^~~~~~~~~~
/home/and/hello/Clipboard/src/clipboard.cpp:432:26: error: ‘stop_token’ is not a member of
std’
/home/and/hello/Clipboard/src/clipboard.cpp: In function ‘void checkItemSize()’:
/home/and/hello/Clipboard/src/clipboard.cpp:503:13: error: ‘indicator’ was not declared in this scope
  503 |             indicator.request_stop();
      |             ^~~~~~~~~
/home/and/hello/Clipboard/src/clipboard.cpp: In function ‘void pasteFiles()’:
/home/and/hello/Clipboard/src/clipboard.cpp:637:25: error: ‘indicator’ was not declared in this scope
  637 |                         indicator.request_stop();
      |                         ^~~~~~~~~
/home/and/hello/Clipboard/src/clipboard.cpp:639:42: error: ‘jthread’ is not a member of ‘st
’; did you mean ‘thread’?
  639 |                         indicator = std::jthread(setupIndicator);
      |                                          ^~~~~~~
      |                                          thread
/home/and/hello/Clipboard/src/clipboard.cpp:639:50: error: ‘setupIndicator’ was not declared in this scope
  639 |                         indicator = std::jthread(setupIndicator);
      |                                                  ^~~~~~~~~~~~~~
/home/and/hello/Clipboard/src/clipboard.cpp: In function ‘int main(int, char**)’:
/home/and/hello/Clipboard/src/clipboard.cpp:778:9: error: ‘indicator’ was not declared in this scope
  778 |         indicator = std::jthread(setupIndicator);
      |         ^~~~~~~~~
/home/and/hello/Clipboard/src/clipboard.cpp:778:26: error: ‘jthread’ is not a member of ‘st
’; did you mean ‘thread’?
  778 |         indicator = std::jthread(setupIndicator);
      |                          ^~~~~~~
      |                          thread
/home/and/hello/Clipboard/src/clipboard.cpp:778:34: error: ‘setupIndicator’ was not declared in this scope
  778 |         indicator = std::jthread(setupIndicator);
      |                                  ^~~~~~~~~~~~~~
/home/and/hello/Clipboard/src/clipboard.cpp:799:9: error: ‘indicator’ was not declared in this scope
  799 |         indicator.request_stop();
      |         ^~~~~~~~~
make[2]: *** [CMakeFiles/clipboard.dir/build.make:76: CMakeFiles/clipboard.dir/src/clipboard.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/clipboard.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by Slackadays** [comment]
You need a compiler that supports at least C++20, so you'll need to install GCC 11 or higher. GCC 10 could work, but last I checked it didn't support a few required features.

**Comment by miguelgargallo** [comment]
Thanks! Great advice

**Comment by miguelgargallo** [comment]
It would be great in case it happen that error, to throw a message to the user with your advice! Nice project!

**Comment by Slackadays** [comment]
I'll see what I can do with adding a warning in the code for this kind of error. :)

**Comment by xdssio** [comment]
I have gcc-12 installed, but still no dice.
error logs:
```
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /Library/Developer/CommandLineTools/usr/bin/c++ 
Build flags: 
Id flags:  

The output was:
1
ld: library not found for -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by Slackadays** [comment]
CMake has a bug where it doesn't see new compilers. Try `cmake Clipboard -D CMAKE_CXX_COMPILER=gcc-12` or the equivalent for how you access `gcc-12` to make CMake see the new compiler.

**Comment by xdssio** [comment]
I've got this `cc1plus: error: '-fno-fat-lto-objects' are supported only with linker plugin` error.
```
-- The CXX compiler identification is GNU 12.2.0
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/bin/gcc-12 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- X11 not found, building without X11 support
-- Wayland not found, building without Wayland support
-- Performing Test COMPILER_SUPPORTS_MARCH_NATIVE
-- Performing Test COMPILER_SUPPORTS_MARCH_NATIVE - Success
-- IPO/LTO not supported: Change Dir: <my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/bin

Run Build Command(s):/usr/bin/make -f Makefile && /usr/local/Cellar/cmake/3.23.2/bin/cmake -S<my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/src -B<my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/bin --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.23.2/bin/cmake -E cmake_progress_start <my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/bin/CMakeFiles <my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/bin//CMakeFiles/progress.marks
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/Makefile2 all
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/foo.dir/build.make CMakeFiles/foo.dir/depend
cd <my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/bin && /usr/local/Cellar/cmake/3.23.2/bin/cmake -E cmake_depends "Unix Makefiles" <my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/src <my path>misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/src <my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/bin <my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/bin <my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/bin/CMakeFiles/foo.dir/DependInfo.cmake
Scanning dependencies of target foo
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/foo.dir/build.make CMakeFiles/foo.dir/build
[ 25%] Building CXX object CMakeFiles/foo.dir/foo.cpp.o
/usr/local/bin/gcc-12   -flto -fno-fat-lto-objects -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk -o CMakeFiles/foo.dir/foo.cpp.o -c <my path>misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/src/foo.cpp
cc1plus: error: '-fno-fat-lto-objects' are supported only with linker plugin
make[2]: *** [CMakeFiles/foo.dir/foo.cpp.o] Error 1
make[1]: *** [CMakeFiles/foo.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by Slackadays** [comment]
Looks like CMake is getting hung up on old configurations, try removing `CMakeCache.txt` and `CMakeFiles` and then redo my command to get CMake to refresh its rules.

**Comment by xdssio** [comment]
```
CXX compiler IPO check failed with the following output:
Change Dir: /<my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/bin

Run Build Command(s):/usr/bin/make -f Makefile && /usr/local/Cellar/cmake/3.23.2/bin/cmake -S/<my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/src -B/<my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/bin --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.23.2/bin/cmake -E cmake_progress_start /<my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/bin/CMakeFiles /<my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/bin//CMakeFiles/progress.marks
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/Makefile2 all
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/foo.dir/build.make CMakeFiles/foo.dir/depend
cd /<my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/bin && /usr/local/Cellar/cmake/3.23.2/bin/cmake -E cmake_depends "Unix Makefiles" /<my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/src /<my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/src /<my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/bin /<my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/bin /<my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/bin/CMakeFiles/foo.dir/DependInfo.cmake
Scanning dependencies of target foo
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/foo.dir/build.make CMakeFiles/foo.dir/build
[ 25%] Building CXX object CMakeFiles/foo.dir/foo.cpp.o
/usr/local/bin/gcc-12   -flto -fno-fat-lto-objects -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk -o CMakeFiles/foo.dir/foo.cpp.o -c /<my path>/misc_projects/tmp/CMakeFiles/_CMakeLTOTest-CXX/src/foo.cpp
cc1plus: error: '-fno-fat-lto-objects' are supported only with linker plugin
make[2]: *** [CMakeFiles/foo.dir/foo.cpp.o] Error 1
make[1]: *** [CMakeFiles/foo.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by xdssio** [comment]
Same.

**Comment by Slackadays** [comment]
Does it actually fail when you do `cmake --build .`? It looks like that error might just be from the IPO check failing and provide its verbose output.

**Comment by xdssio** [comment]
```
$ cmake --build .
Consolidate compiler generated dependencies of target clipboard
[ 50%] Linking CXX executable clipboard
ld: warning: option -s is obsolete and being ignored
ld: can't write output file to 'clipboard' because that path is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [clipboard] Error 1
make[1]: *** [CMakeFiles/clipboard.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by Slackadays** [comment]
When you cloned Clipboard, it looks like you cloned it as `.../clipboard` and not `.../Clipboard` as in the readme, so you'll need to rename the directory to `Clipboard` and not `clipboard`.

**Comment by xdssio** [comment]
I did clone it as such, it is named Clipboard.

**Comment by Slackadays** [comment]
What's in the `clipboard` directory?

**Comment by arisolt** [comment]
If you already ran `cmake Clipboard` once, you won't be able to convince cmake to use a different compiler, even if you run the command again. You should delete the directory, clone the repo again and start over. Ideally, the installation instructions should have used the recommended method of building inside a dedicated `/build/` directory, which could then be deleted so you could start over without having to clone the repo again. 

Like so:
```
cd Clipboard
mkdir build
CC=gcc-12 CXX=gxx-12 cmake ..
cmake --build .
```

**Comment by slotrans** [comment]
> What's in the `clipboard` directory?

The Mac filesystem is case-preserving-but-not-case-sensitive. If there is a "Clipboard" directory, the file "clipboard" cannot be written.

The compile instructions seem weird to me in that they ask you to run cmake from one directory level up, which is what causes the above error. I had better luck with:
```
git clone https://github.com/slackadays/Clipboard
cd Clipboard
cmake .
cmake --build .
``

Though, the resulting binary does not work:
```
% cmake --build .
[ 50%] Building CXX object CMakeFiles/clipboard.dir/src/clipboard.cpp.o
[100%] Linking CXX executable clipboard
ld: warning: option -s is obsolete and being ignored
[100%] Built target clipboard

% ./clipboard
libunwind: _Unwind_GetDataRelBase - _Unwind_GetDataRelBase() not implemented
zsh: abort      ./clipboard
```
This is on an M1 Mac, OS X 12.5, gcc 12.2.0

**Comment by Slackadays** [comment]
Readme has been updated to include `cd clipboard`, `libunwind` will require some future testing

**Comment by Slackadays** [comment]
> % ./clipboard
> libunwind: _Unwind_GetDataRelBase - _Unwind_GetDataRelBase() not implemented
> zsh: abort      ./clipboard
> 
> This is on an M1 Mac, OS X 12.5, gcc 12.2.0

Unfortunately, I'm unable to reproduce this on my M1 Mac provided by MacStadium running 11.6, also with GCC 12.2.0. However, judging by your relative newness compared to my Mac, this is highly likely to be a libc++ bug or some kind of Homebrew issue because searching the relevant error only gives the source code in question, which references some nonsense internal alignment checks. Here's what I got:

```
administrator@45165 Clipboard % cmake --build .
[ 50%] Building CXX object CMakeFiles/clipboard.dir/src/clipboard.cpp.o
[100%] Linking CXX executable clipboard
ld: warning: option -s is obsolete and being ignored
[100%] Built target clipboard
administrator@45165 Clipboard % ./clipboard 
• There are items in these clipboards: 0
Add cut, copy, or paste to the end, like clipboard copy to get started, or if you need help, try clipboard -h to show the help screen.
```

**Comment by Slackadays** [comment]
@miguelgargallo std::jthread has been removed from Clipboard, and now all builds should work

**Comment by xdssio** [comment]
Works for me now.

Thanks!
