### ISSUE TITLE
update issue for copied file in Windows

### ISSUE THREAD

**Issue by Jaehaks** [Slackadays/Clipboard#200]
**Describe the bug**
If I copy a file which is included before copied in windows manager, 
`cb info` and clipboard don't update the list of copied items

**To Reproduce**
1. copy some files (these 3 files)
![image](https://github.com/user-attachments/assets/69fcdb86-5027-46d7-a263-1ca7bb2a92de)
2. check `cb info` 
![image](https://github.com/user-attachments/assets/e4b02c6e-a4dd-4b2e-8584-4decd3344331)
3. copy files parts of the copied files
![image](https://github.com/user-attachments/assets/7ea8eddb-fbb8-4939-84b5-4555f9cd997c)
4. check `cb info`
![image](https://github.com/user-attachments/assets/4fc57828-66b8-45c3-bf08-05fe47953419)

the result is same. not different
But If other files which is not included in copied item before. the info is updated.

**Expected behavior**
clipboard updates at every copy case

**Screenshots**
mentioned above

**Version**
![image](https://github.com/user-attachments/assets/9ac70aa0-3bce-47af-a3db-7e6ebf50e54e)

**Additional context**

**Before you post**
Please make sure you check previous bug reports before filing a new one.
This will help keep the Issues section less cluttered. :)
Feel free to delete this section once you've completed this form.

**Comment by Slackadays** [comment]
Fixed in https://github.com/Slackadays/Clipboard/commit/c11f2ba978e398e54995b96d3cc291b81465d008
