### ISSUE TITLE
Issue with the archives' name in the latest 0.10.0 release

### ISSUE THREAD

**Issue by Antiz96** [Slackadays/Clipboard#210]
**Describe the bug**
The archives for prebuilt binaries in the latest 0.10.0 release seems to have an extra digit in their names:

- clipboard-linux-amd64.**4.**zip 
- clipboard-linux-arm64.**3.**zip 
- clipboard-linux-riscv64.**3.**zip 
- [...]

Is this intended?

**Comment by Slackadays** [comment]
I don't know how I forgot to change those (they come from downloading GHA artifacts) but it's fixed not.
