### ISSUE TITLE
Feature Request: PuTTY & similar interoperability

### ISSUE THREAD

**Issue by Gaibhne** [Slackadays/Clipboard#23]
**Is your feature request related to a problem? Please describe.**
I have absolutely no idea if this is in any way technically possible, but I for one use terminals exclusively through tools such as PuTTY/KiTTY, Tabby and others like it. Clipboard does me little good unless the contents can be shared through the terminal tool I use.

**Describe the solution you'd like**
Support for the mentioned tools, or a mention in the README that such tools can't be supported due to technical limitations.

**Comment by Slackadays** [comment]
I've done some research on this and it looks to be impossible unless I made some kind of Clipboard Daemon that automatically syncs with SSH sessions, and that's going to be an absolute nightmare that won't integrate well with the current Clipboard system. So, I'm going to have to say that this can't realistically be done. :(

**Comment by Slackadays** [comment]
However, there are a few similar tools like `sshfs` and `scp` that you could actually use with Clipboard to sync the temporary folder across the two filesystems.

**Comment by Slackadays** [comment]
Now that I think about it, `sshfs` would work great here. If you can mount `/tmp/Clipboard` on the remote system onto yours, then Clipboard should work seamlessly across the two systems in theory.

**Comment by Gaibhne** [comment]
Thanks, I'll look into it. Would still recommend putting something along those lines in the readme, because I predict I'm not going to be the only one to ask.

**Comment by Slackadays** [comment]
Now in the wiki! https://github.com/Slackadays/Clipboard/wiki/Clipboard-Across-Two-Systems
