### ISSUE TITLE
Syntax and documentation of the persistent clipboard

### ISSUE THREAD

**Issue by epmoyer** [Slackadays/Clipboard#37]
The issues below are all related.  I'd be happy to put a PR together if you like, but there are some decisions to be made below so I didn't want to do that unless you were interested and had weighed in on the perma_clip syntax, and on the `CLIPBOARD_TMPDIR`/`CLIPBOARD_PERSISTENT` subject.

## 1) Help Text
The help instructions for using the permanent clipboard are incorrect.  The built-in help says `You can also choose which clipboard you want to use by adding a number to the end, or - to use a permanent clipboard.` but the actual syntax is to use one of `_:;|` (rather than `-`) per this line in `clipboard.cpp`:

```
            clipboard_name = clipboard_name.substr(clipboard_name.find_first_of("_:;|") + 1);
```

## 2) Naming (persistent vs permanent)
I think it would also be helpful to harmonize the language in the code with the language in the help/docs, and use `persistent` (rather than `permanent`) everywhere, so...
- Help becomes:
    - `You can also choose which clipboard you want to use by adding a number to the end, or one of "_:;|" to use a persestent clipboard.`
- `copying.use_perma_clip` -> `copying.use_persistent_clip` 
- `filepath.persistent` and `constants.persistent_directory_name ` remain as they are

## 3) Invocation syntax
The invocation syntax in the `README.md` (and the `man.md`) does not mention the `_:;|` syntax for permanent/persistent clipboards.  If you really want to support all of `_:;|` then writing the syntax gets hard because `|` is usually an OR in command line syntax.  If you dropped the `|` then you could write something like:

**Copy**   `clipboard ([--]copy|[-]cp[_|:|;][(id)]) (file) [files]`

But that's pretty verbose.  I don't know the historical reason for allowing all of `_:;|`; it seems like selecting and committing to a single character would be more clear and easier to document.

## 4) `[(id)]` missing from README.md

The `[(id)]` parameter appears in the invocation syntax in `man.md` (and the subsequently generated `man.1`), but not in the invocation syntax in `README.md`.

## 5) TMPDIR

The way the `README.md` is worded suggests that one might change `TMPDIR` to change where the temporary clipboards are stored, but my understanding is that `TMPDIR` is a "system" env var also used by other programs to determine where to store their temp data.  I think the wording should reflect that, and that if you really want a way to override Clipboard's (and only Clipboard's) temp location then there should be a new environment var (like `CLIPBOARD_TMPDIR`) which (if set) would do that.

## 6) Forcing Persistent

The reason I uncovered all of the above was because I just wanted all my clipboard data to always go to `~/.clipboard/` (i.e. the persistent clipboard) and I couldn't find a way to do that.  Changing `TMPDIR` is inappropriate, and remembering to type one of `_:;|` is cumbersome.  In the end I just hacked my local version to always use perma_clip.  

It would be nice to have either a `CLIPBOARD_TMPDIR` env var that could override (just Clipboard's) temp dir, or alternatively a `CLIPBOARD_PERSISTENT` env var that, if set, would force perma_clip.

My local hack looks like this:
![always_perma](https://user-images.githubusercontent.com/136718/210699933-5b115c98-9969-4a83-92e9-7e1db152bbe0.png)

Thanks for putting this tool together; I'm glad to have it in my back pocket!
Cheers!

**Comment by Slackadays** [comment]
Done, fixed in commit https://github.com/Slackadays/Clipboard/commit/f4ac182e13f9fadaedaeea7f976ea373b773d768 (added extra environment vars that you can configure and unified documentation)

**Comment by epmoyer** [comment]
Nicely done, thanks!
