### ISSUE TITLE
Error during installation: ranges: No such file or directory

### ISSUE THREAD

**Issue by dieterwalckiers** [Slackadays/Clipboard#45]
**Describe the bug**
When running the installation, I get following error on the `cmake --build .` step:
```[ 16%] Building CXX object src/clipboardx11/CMakeFiles/clipboardx11.dir/src/x11.cpp.o
/home/dyte/temp/Clipboard/src/clipboardx11/src/x11.cpp:23:10: fatal error: ranges: No such file or directory
   23 | #include <ranges>
      |          ^~~~~~~~
compilation terminated.
make[2]: *** [src/clipboardx11/CMakeFiles/clipboardx11.dir/build.make:63: src/clipboardx11/CMakeFiles/clipboardx11.dir/src/x11.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:136: src/clipboardx11/CMakeFiles/clipboardx11.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**To Reproduce**
1. Run the manual installation up until `cmake --build .`

**Expected behavior**
The installation finishes succesfully

**Additional context**
I'm on Ubuntu 20.04.1 LTS

**Comment by Slackadays** [comment]
Unfortunately, Clipboard only supports platforms that support C++20, which it looks like yours doesn't. Is it possible for you to install GCC 10 with `sudo apt install g++-10` and then do the Manual Installation commands?

**Comment by dieterwalckiers** [comment]
I installed gcc 10 using your command, and reran the manual installation.
Unfortunately the same command failed with the same message. Too bad. Cool project though!

**Comment by Slackadays** [comment]
You'll also need to do `cmake .. -DCMAKE_CXX_COMPILER=g++-10` to make CMake see the new compiler, so try that before giving up :)

**Comment by dieterwalckiers** [comment]
That make the install go through, thanks!

But now I see some strange behaviour in the usage:
When I try to copy a file with `cb cp <filepath>`, I get following output, while some process is still running, because I don't return to my command line. I can't even easily Ctrl+C out of it, I need to close my terminal. This is the output:

![Screenshot_2023-01-12_16-02-13](https://user-images.githubusercontent.com/12844544/212101821-fcfa1629-d92d-4b82-81c5-0f977a7e3ca5.png)

**Comment by Slackadays** [comment]
Oops, you may have forgotten to also add `-DCMAKE_BUILD_TYPE=MinSizeRel` to `cmake ..`, as you're seeing the Debug messages.

**Comment by dieterwalckiers** [comment]
Thanks so much for your help, working perfectly now!
