### ISSUE TITLE
Windows installation won't work without Cmake, users should not have to build from source

### ISSUE THREAD

**Issue by ofersadan85** [Slackadays/Clipboard#46]
**Is your feature request related to a problem? Please describe.**
Windows installation instructions very unclear, overly complicated, error out when `cmake` is not installed (which is the case for most users)

**Describe the solution you'd like**
The installation instructions in the `README.md` file should be to download the already built artifact for windows, and install it to somewhere in the user's `$PATH`

**Describe alternatives you've considered**
Either `install.ps1` needs to be replaced, or there needs to be a better alternative that doesn't build from source (just download the artifact) in the readme

**Additional context**
See further notes about this process that I wrote [here](https://github.com/Slackadays/Clipboard/pull/44#issuecomment-1380171172) in #44 
I'll be happy to write up a pull request for this feature if you're interested (should be pretty straight forward), if so let me know

**Comment by ofersadan85** [comment]
Note: Just tested the installation on Linux as well, 2 problems there.
1. Cmake is also required, and building from source, this is the same problem as described above
2. Running the installation command in the readme leads to this error
> sh: 2: set: Illegal option -o pipefail

This is because `sh` is used when `bash` is needed... the correct command should be 

    curl -sSL https://github.com/Slackadays/Clipboard/raw/main/install.sh | bash

Which works fine, but is very long because it's building from source, and leaves the `Clipboard` directory left over from the process

**Comment by Slackadays** [comment]
Would downloading an artifact from GH Actions work?

**Comment by ofersadan85** [comment]
@Slackadays if i go to where your readme points [https://nightly.link/Slackadays/Clipboard/workflows/main/main](https://nightly.link/Slackadays/Clipboard/workflows/main/main) the file there is zipped, but if i unpack it to my `$PATH` everything works as expected

**Comment by Slackadays** [comment]
Then I can make the script download that artifact and unpack it somewhere in `$PATH`, and this problem is fixed.

**Comment by Slackadays** [comment]
@ofersadan85 Would it be better to download the artifact or just install CMake with `winget install Kitware.CMake`?

**Comment by ofersadan85** [comment]
I think the artifact is the more portable approach, it's just a file. Not every Windows installation has `winget` (most updated Windows 11 do have it if I'm not mistaken, but certainly not windows servers). Same probably goes for Linux (I'm not aware of any disto that doesn't have Cmake by default, but some probably don't)

**Comment by ofersadan85** [comment]
Plus this way you don't force the users to build from source, which isn't terribly long, but compare that to an "installation" of just downloading a 200KB file

**Comment by Slackadays** [comment]
Done, fixed in https://github.com/Slackadays/Clipboard/commit/24e34046fdebc7d166afe873c95c621fd4fcc312 and Linux now uses `bash`
