### ISSUE TITLE
aur pkbuild CMAKE_BUILD_TYPE

### ISSUE THREAD

**Issue by doums** [Slackadays/Clipboard#47]
Not a bug but rather a question, is there any reason why you use CMAKE_BUILD_TYPE set to `none` instead of `MinSizeRel` for the AUR package?

**Comment by Slackadays** [comment]
I don't choose what goes in the AUR package, but @Antiz96 might.

**Comment by Antiz96** [comment]
Hi @doums,

The `DCMAKE_BUILD_TYPE` is set to `none` according to [Arch's CMAKE packaging guidelines](https://wiki.archlinux.org/title/CMake_package_guidelines).
See https://wiki.archlinux.org/title/CMake_package_guidelines#CMake_can_automatically_override_the_default_compiler_optimization_flag and https://wiki.archlinux.org/title/CMake_package_guidelines#Fixing_the_automatic_optimization_flag_override for more details about this specific recommendation.

**Comment by Slackadays** [comment]
Does Arch apply `DNDEBUG` by default? If not, then Clipboard may show a lot of ugly debug messages.

**Comment by doums** [comment]
Hi @Antiz96, that's interesting, thx for providing the doc bits ;) Not so simple as I expected.

**Comment by Antiz96** [comment]
> Does Arch apply `DNDEBUG` by default? If not, then Clipboard may show a lot of ugly debug messages.

Looks like it does not, I haven't paid attention to that before... Sorry about that!
As a workaround, I made a new release of the PKGBUILDs which defines the DNDEBUG flags inside the `build()` function like so:
```
build () {
        cmake -B build -S "${_pkgname}-${pkgver}" \
                -DCMAKE_BUILD_TYPE='None' \
                -DCMAKE_INSTALL_PREFIX='/usr' \
                -DCMAKE_C_FLAGS=-DNDEBUG \
                -DCMAKE_CXX_FLAGS=-DNDEBUG \
                -Wno-dev
        cmake --build build
}
```

**Comment by Antiz96** [comment]
> > Does Arch apply `DNDEBUG` by default? If not, then Clipboard may show a lot of ugly debug messages.
> 
> Looks like it does not, I haven't paid attention to that before... Sorry about that! As a workaround, I made a new release of the PKGBUILDs which defines the DNDEBUG flags inside the `build()` function like so:
> 
> ```
> build () {
>         cmake -B build -S "${_pkgname}-${pkgver}" \
>                 -DCMAKE_BUILD_TYPE='None' \
>                 -DCMAKE_INSTALL_PREFIX='/usr' \
>                 -DCMAKE_C_FLAGS=-DNDEBUG \
>                 -DCMAKE_CXX_FLAGS=-DNDEBUG \
>                 -Wno-dev
>         cmake --build build
> }
> ```

For references:
https://aur.archlinux.org/cgit/aur.git/commit/?h=clipboard&id=91be2852410a982b30bc6011afcb74e7fd9f0313
https://aur.archlinux.org/cgit/aur.git/commit/?h=clipboard-git&id=86f7d1367017da7bf03c7705a19ffa0dacb59d77

**Comment by Slackadays** [comment]
This is interesting, so Arch also applies `-O2` for all packages?

**Comment by Antiz96** [comment]
> This is interesting, so Arch also applies `-O2` for all packages?

Yup. `-O2` is the default flag defined in the `makepkg` configuration file and (except for some specific cases), it is used for all Arch packages.
