### ISSUE TITLE
Suggestion: shortcuts, like cp and mv

### ISSUE THREAD

**Issue by jabbalaci** [Slackadays/Clipboard#5]
I would like to use some shortcuts:

- `cb mv` for moving a file to the clipboard
- `cb cp` for copying a file to the clipboard
- I noticed that `cb p` works for pasting from the clipboard

These should also appear in the help.

**Comment by Slackadays** [comment]
Almost already here, since Clipboard only compares the first two characters for the actions. That means you can do `cb cu` for cut, `cb co` for copy, and `cb p` for paste as you already found. I could also add your shorthands for even better UX, so there's that.

**Comment by Slackadays** [comment]
Done, added in latest commit

**Comment by jabbalaci** [comment]
Thanks!
