### ISSUE TITLE
Install script side effects

### ISSUE THREAD

**Issue by Posejdos** [Slackadays/Clipboard#51]
The install script _(install.sh)_ calls `rm -r bin lib` at the end of the installation.
This will delete any existing _bin_ and _lib_ folders in the working directory.

This happened to me - I called your script as described in _README.md_ in my home directory,
where I also store a _bin_ folder with all my useful scripts.

It's my fault for calling scripts from the internet without looking at them first, but maybe we can
save someone else from feeling the pain I'm feeling now...

**To Reproduce**
1. `mkdir test`
2. `cd test`
3. `mkdir bin`
4.  `curl -sSL https://github.com/Slackadays/Clipboard/raw/main/src/install.sh | bash`
5.  _bin_ folder has been removed.

**Expected behavior**
Clipboard should install, but without any side effects.

I think the install script could create a unique, temporary directory instead of doing its work in
the working directory.

**Comment by Slackadays** [comment]
Did you restore your files from a backup?

**Comment by Posejdos** [comment]
I did restore some of them, but only some - that's what I get for doing backups only once a year :smile: 
These things happen, no big deal.
