### ISSUE TITLE
Add instructions on how to uninstall

### ISSUE THREAD

**Issue by PlexSheep** [Slackadays/Clipboard#6]
While installation is covered in the README, uninstalling is not. To install the AUR package of this software, i had to manually remove `/usr/bin/cb` and `/usr/bin/clipboard`. I am not sure if that was all i had to remove?

Something like ``cmake --uninstall .`` would be helpful.

**Comment by Slackadays** [comment]
Done, you can uninstall using `sudo xargs rm < install_manifest.txt` as given by the CMake docs and I also added it to the readme.
