### ISSUE TITLE
installing via curl method fails on nixos

### ISSUE THREAD

**Issue by o69mar** [Slackadays/Clipboard#66]
when i curled the script to install clipboard, there were some errors. first it couldn't find `unzip` and also, it tries to install clipboard to `/usr/bin/` which has nothing but `env` on nixos. everything is on `/run/current-system/sw/` that has `bin`, `etc`, `lib`, `share` and etc.  because of this i also got `No such file or directory` errors. i could make a PR to fix this problem, or you could just make a nix flake for clipboard.

also the nixos pkg version of clipboard has been removed for some reason

**Comment by Slackadays** [comment]
A PR would be great, as you're running nix but I'm not, so you can test it easier. :)

**Comment by o69mar** [comment]
> A PR would be great, as you're running nix but I'm not, so you can test it easier. :)

because i didn't know how to make a nix flake, i turned to the shell script, however copying any file to `/run/current-system/sw` results in a error which says `Read-only file system`, the clipboard executable can still be installed but the so files cannot be installed.

**Comment by Slackadays** [comment]
The .so files can be placed in the same directory as the binary, so would that work?

**Comment by o69mar** [comment]
> The .so files can be placed in the same directory as the binary, so would that work?

yup

**Comment by o69mar** [comment]
> The .so files can be placed in the same directory as the binary, so would that work?

for some reason when i try to execute clipboard, an error pops up by `exec`

**Comment by o69mar** [comment]
@Slackadays i get this error for some reason

![image](https://user-images.githubusercontent.com/119129086/217540705-6fb37d39-64cf-4388-abf7-8dbd38326f63.png)

**Comment by Slackadays** [comment]
What does `file` show you? It looks like maybe `clipboard` isn't actually a program or maybe there's a compiler bug.

**Comment by o69mar** [comment]
> What does `file` show you? It looks like maybe `clipboard` isn't actually a program or maybe there's a compiler bug.

i think the interpreter is the problem, because `/lib64` doesn't exist

![image](https://user-images.githubusercontent.com/119129086/217579668-fa0b7251-81fa-490f-a7c5-151c62945a2a.png)

**Comment by o69mar** [comment]
> You could just add a case for NixOS where it compiles Clipboard instead, as that's the most generic option in the script
> 
> The compile section is at the end of the script

okay. i'll try it

**Comment by o69mar** [comment]
> You could just add a case for NixOS where it compiles Clipboard instead, as that's the most generic option in the script
> 
> The compile section is at the end of the script

i compiled clipboard and it worked, here is the output of `file`, seems like it points to the correct interpreter

<img src="https://cdn.discordapp.com/attachments/1068228928721928283/1072908630598357103/2023-02-08-185434_1743x102_scrot.png">

**Comment by o69mar** [comment]
fixed in #71
