### ISSUE TITLE
piping zero bytes

### ISSUE THREAD

**Issue by muralikodali** [Slackadays/Clipboard#7]
clipboard is piping out zero bytes, when i try to paste the clipboard content to
some file or stdout as shown below.

![screenshot_20221212104633](https://user-images.githubusercontent.com/11482766/206966475-70bbd99b-fb10-41a6-9aa9-2805309cb0a6.png)

**Comment by Slackadays** [comment]
fixed in latest commit https://github.com/Slackadays/Clipboard/commit/5bc5033873e84da80ef635b452517b8440346dc1 

https://github.com/Slackadays/Clipboard/actions/runs/3672987062

the issue was that Clipboard assumed the input was piped in, while we just want everything that's been copied
