### ISSUE TITLE
clipboard paste giving ^M characters

### ISSUE THREAD

**Issue by muralikodali** [Slackadays/Clipboard#8]
when tried to paste into vim using `:r !clipboard paste` it is giving ^M characters in the output.

![screenshot_20221212122600](https://user-images.githubusercontent.com/11482766/206981063-23f91c2d-3dbe-4041-a432-d06dd128765c.png)

is there any option to escape these ^M characters?

**Comment by Slackadays** [comment]
^M is the carriage return character, and there is only one place in Clipboard that makes those. So it looks like I'll have to change the way that place works so that this doesn't happen

**Comment by Slackadays** [comment]
Also check this because your document may be in the wrong format: https://unix.stackexchange.com/questions/32001/what-is-m-and-how-do-i-get-rid-of-it

**Comment by muralikodali** [comment]
with latest commit, there are no ^M chartacters. but ^H characters are appearing.

i have copied the `Makefile` in Clipboard repo and tried to paste in vim buffer.

it is also getting `piping out...` line to buffer.

pasted file is attached.

[testcb.txt](https://github.com/Slackadays/Clipboard/files/10215469/testcb.txt)

**Comment by Slackadays** [comment]
Fixed in latest commit https://github.com/Slackadays/Clipboard/commit/851286521c8d780bcb1a19e32b0e1ba110ce1acf, normal output like `piping out...` should now not appear in vim but errors in syntax might. Notify me if you still get the same issue as before
