### ISSUE TITLE
cb clr doesn't work on mac

### ISSUE THREAD

**Issue by phoenixuprising** [Slackadays/Clipboard#80]
**Describe the bug**
It appears that `cb clr` does not work on an M1 mac running 13.2. 

**To Reproduce**
1. `echo "foo" | cb`
```
✓ Copied 4 bytes
```
2. `cb`
```
• There are items in these clipboards:
▏ 0: foo
```
3. `cb clr`
```
✓ Cleared the clipboard... 0%
```
4. `cb`
```
• There are items in these clipboards:
▏ 0: foo
```

**Expected behavior**
I expect there to be zero items in the clipboard.

**Screenshots**
<img width="1624" alt="Screenshot 2023-02-15 at 8 30 59 PM" src="https://user-images.githubusercontent.com/249516/219261408-ebfc4839-1ae7-4688-b71b-e9c4e231ec6b.png">

**Comment by Slackadays** [comment]
I know why this happens. Clipboard doesn't clear the macOS clipboard when writing to it, so the new, "empty" clipboard never makes it to the system. Now that it doesn't get erased, Clipboard will read this data when you run it again and syn with it, bringing back what you tried to clear.

**Comment by Slackadays** [comment]
Does using the latest commit fix your problem?

**Comment by Slackadays** [comment]
@phoenixuprising Does using the latest commit fix your problem?

**Comment by Slackadays** [comment]
Fixed in latest commit
