### ISSUE TITLE
Option to mute the help text when running `cb` with no params

### ISSUE THREAD

**Issue by phoenixuprising** [Slackadays/Clipboard#81]
**Is your feature request related to a problem? Please describe.**
It'd be nice if there was an environment variable that allows muting the help text after running `cb` with no options.
```
cb
• There are items in these clipboards:
▏ 0: foo
▏ 1: foo2
Add cut, copy, or paste to the end, like clipboard copy to get started, or if you need help, try clipboard -h to show the help screen.
```
It just feels very noisy to look at the cb real quick. 

**Describe the solution you'd like**
`CLIPBOARD_SILENCE_HELP` environment variable

**Comment by Slackadays** [comment]
I just changed the message to only show up when you're trying to paste an empty clipboard, so now it's only noisy when you're doing something wrong.
