### ISSUE TITLE
Can't install getting `GLIBC_2.32' not found 

### ISSUE THREAD

**Issue by abuseofnotation** [Slackadays/Clipboard#85]
![image](https://user-images.githubusercontent.com/4872512/219458348-494443e7-9d3c-44a7-b966-8d7ca769d766.png)

Tried and didn't help:
apt install -y libc6 libc-bin

**Comment by Slackadays** [comment]
Dupe of #50, compile Clipboard manually with GCC 11 or newer or upgrade your OS.
