### ISSUE TITLE
Option to install with `brew`

### ISSUE THREAD

**Issue by lukasz-mitka** [Slackadays/Clipboard#88]
**Is your feature request related to a problem? Please describe.**
I'd like to use familiar way of installing this app

**Describe the solution you'd like**
`brew install clipboard`

**Describe alternatives you've considered**
existing installation methods

**Additional context**
brew works for both Mac and Linux btw.

**Comment by Slackadays** [comment]
Already in progress https://github.com/Homebrew/homebrew-core/pull/120917

**Comment by o69mar** [comment]
> Already in progress [Homebrew/homebrew-core#120917](https://github.com/Homebrew/homebrew-core/pull/120917)

and also nixos aswell https://github.com/NixOS/nixpkgs/pull/207928

**Comment by Slackadays** [comment]
I just got an Android TV box just for Clipboard development today, so that's coming soon :)

**Comment by tranzystorek-io** [comment]
@lukasz-mitka homebrew has landed! 🎉
