### ISSUE TITLE
copy files large than free space

### ISSUE THREAD

**Issue by Martinits** [Slackadays/Clipboard#96]
If copy a big file larger than free space, there will be an error:
`There won't be enough storage available to paste everything.`
When I have another storage mounted which has enough free space and I'm going to paste there, that error will occur.
Maybe it detects free space of `/` only?
Or could you postpone this error till the paste operation?

**Comment by Slackadays** [comment]
Done, fixed in https://github.com/Slackadays/Clipboard/commit/98c59c3b646487ae70085b183029df1100a80a5b
