### ISSUE TITLE
Processes hanging

### ISSUE THREAD

**Issue by pidario** [Slackadays/Clipboard#99]
**Describe the bug**
Every time I launch `clipboard clear` I got a bunch of processes lying around.

**To Reproduce**
- Install clipboard from the `AUR` repo `clipboard-bin`.
- Launch `clipboard clear` multiple time
- Furthermore, if I copy a file, for example with `cb cp .xinitrc` I correctly expect the process to stay. But once I `cb clear` I expect it to exit, but that does not seem to be the case.

**Expected behavior**
Processes should exit with some status code, unless they are needed for some reason.
I did not try to compile it myself to see if this is an issue with the package. Besides, I don't think you maintain any of the `AUR` packages `clipboard-bin` or `clipboard-git`, do you?

**Screenshots**
![2023-02-27T123146](https://user-images.githubusercontent.com/3647292/221553204-81960ce1-574c-4a12-95bd-27416b6031b8.png)

On another notice, I read #95. I believe `Clipboard` is the best tool for clipboard interaction. As a matter of fact, as of today you have 2713 stars on github, kudos! Keep up the good work.

**Comment by Slackadays** [comment]
Done, fixed in https://github.com/Slackadays/Clipboard/commit/bb3128a273d74282bde0e5861214ea1166b3f119 (thanks for the compliments! :)

**Comment by pidario** [comment]
Perfect, fixed in under two hours. You deserved all those :)
